# **DEEP LEARNING MODELLING: LSTM MODEL WITHOUT GEOGRAPHICAL COORDINATES**

## **1. LIBRARIES**

### **1.1 DEPENDENCIES**

In [ ]:
! pip install adlfs azure-storage-blob
! pip install tensorflow
! pip install tqdm

Collecting adlfs
  Downloading adlfs-2024.12.0-py3-none-any.whl.metadata (7.7 kB)
Collecting azure-storage-blob
  Downloading azure_storage_blob-12.26.0-py3-none-any.whl.metadata (26 kB)
Collecting azure-core<2.0.0,>=1.28.0 (from adlfs)
  Downloading azure_core-1.35.0-py3-none-any.whl.metadata (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.4/44.4 kB 2.2 MB/s eta 0:00:00
Collecting azure-datalake-store<0.1,>=0.0.53 (from adlfs)
  Downloading azure_datalake_store-0.0.53-py2.py3-none-any.whl.metadata (19 kB)
Collecting azure-identity (from adlfs)
  Downloading azure_identity-1.24.0-py3-none-any.whl.metadata (86 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 kB 4.4 MB/s eta 0:00:00
Requirement already satisfied: fsspec>=2023.12.0 in /usr/local/lib/python3.11/dist-packages (from adlfs) (2025.3.0)
Requirement already satisfied: aiohttp>=3.7.0 in /usr/local/lib/python3.11/dist-packages (from adlfs) (3.12.15)
Requirement already satisfied: cryptography>=2.1.4 in /usr/local/lib/python3.11/dist-packages (from azure-storage-blob) (43.0.3)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from azure-storage-blob) (4.14.1)
Collecting isodate>=0.6.1 (from azure-storage-blob)
  Downloading isodate-0.7.2-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (6.6.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (1.20.1)
Requirement already satisfied: requests>=2.21.0 in /usr/local/lib/python3.11/dist-packages (from azure-core<2.0.0,>=1.28.0->adlfs) (2.32.3)
Requirement already satisfied: six>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from azure-core<2.0.0,>=1.28.0->adlfs) (1.17.0)
Requirement already satisfied: cffi in /usr/local/lib/python3.11/dist-packages (from azure-datalake-store<0.1,>=0.0.53->adlfs) (1.17.1)
Collecting msal<2,>=1.16.0 (from azure-datalake-store<0.1,>=0.0.53->adlfs)
  Downloading msal-1.33.0-py3-none-any.whl.metadata (11 kB)
Collecting msal-extensions>=1.2.0 (from azure-identity->adlfs)
  Downloading msal_extensions-1.3.1-py3-none-any.whl.metadata (7.8 kB)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi->azure-datalake-store<0.1,>=0.0.53->adlfs) (2.22)
Requirement already satisfied: PyJWT<3,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from PyJWT[crypto]<3,>=1.0.0->msal<2,>=1.16.0->azure-datalake-store<0.1,>=0.0.53->adlfs) (2.10.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.21.0->azure-core<2.0.0,>=1.28.0->adlfs) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.21.0->azure-core<2.0.0,>=1.28.0->adlfs) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.21.0->azure-core<2.0.0,>=1.28.0->adlfs) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.21.0->azure-core<2.0.0,>=1.28.0->adlfs) (2025.8.3)
Downloading adlfs-2024.12.0-py3-none-any.whl (41 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.8/41.8 kB 3.1 MB/s eta 0:00:00
Downloading azure_storage_blob-12.26.0-py3-none-any.whl (412 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 412.9/412.9 kB 17.5 MB/s eta 0:00:00
Downloading azure_core-1.35.0-py3-none-any.whl (210 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 210.7/210.7 kB 19.3 MB/s eta 0:00:00
Downloading azure_datalake_store-0.0.53-py2.py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.3/55.3 kB 5.2 MB/s eta 0:00:00
Downloading isodate-0.7.2-py3-none-any.whl (22 kB)
Downloading azure_identity-1.24.0-py3-none-any.whl (187 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 187.9/187.9 kB 19.0 MB/s eta 0:00:00
Downloading msal-1.33.0-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.9/116.9 kB 10.8 MB/s eta 0:00:00
Downloading msal_extensions-1.3.1-py3-none-any.whl (20 kB)
Installing collected packages: isodate, azure-core, azure-storage-blob, msal, msal-extensions, azure-datalake-store, azure-identity, adlfs
Successfully installed adlfs-2024.12.0 azure-core-1.35.0 azure-datalake-store-0.0.53 azure-identity-1.24.0 azure-storage-blob-12.26.0 isodate-0.7.2 msal-1.33.0 msal-extensions-1.3.1
Requirement already satisfied: tensorflow in /usr/local/lib/python3.11/dist-packages (2.19.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (25.2.10)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from tensorflow) (25.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (5.29.5)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (2.32.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.1.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (4.14.1)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.17.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.74.0)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.10.0)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.5.3)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.37.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in /usr/local/lib/python3.11/dist-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.11/dist-packages (from keras>=3.5.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.11/dist-packages (from keras>=3.5.0->tensorflow) (0.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (2025.8.3)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.11/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.8.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from tensorboard~=2.19.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.1.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.11/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow) (3.0.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.5.0->tensorflow) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.5.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (4.67.1)

### **1.2 LIBRARIES**

In [ ]:
# STANDARD LIBRARY
import os
import io
import random

# DATA MANIPULATION AND ANALYSIS
import pandas as pd
import numpy as np

# DATA VISUALISATION
import matplotlib.pyplot as plt
import seaborn as sns

# AZURE CLOUD STORAGE
from adlfs import AzureBlobFileSystem
from azure.storage.blob import BlobServiceClient

# REGULAR EXPRESSIONS
import re

# TIME SERIES
from sklearn.model_selection import TimeSeriesSplit

# STANDARIZATION
from sklearn.preprocessing import StandardScaler

# EVALUATION METRICS
from sklearn.metrics import r2_score

# PROGRESS BAR
from tqdm import tqdm

# TENSORFLOW
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, LSTM, Dense, Dropout
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras import regularizers
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import mixed_precision
mixed_precision.set_global_policy("mixed_float16")

# SEEDS
random.seed(42)
np.random.seed(42)
tf.random.set_seed(42)

In [ ]:
print(tf.__version__)

2.19.0

In [ ]:
# Correctly set pandas display option for max columns and rows
pd.options.display.max_columns = None
pd.options.display.max_rows = None

## **2. LOADING DATASETS FROM AZURE BLOB STORAGE**

In [ ]:
def load_csv_from_blob(blob_name):
    blob_client = container_client.get_blob_client(blob_name)
    stream = blob_client.download_blob()
    data_bytes = stream.readall()
    data_str = data_bytes.decode("utf-8")
    return pd.read_csv(io.StringIO(data_str))


# Connection configuration
AZURE_STORAGE_ACCOUNT = "researchprojectx24104515"
AZURE_STORAGE_KEY = "bxpexO6i+Hz6n1WiipTn+sTCuLPGMS1BogMERrIrHd16DpQ0GLfQ0R33yrSw4MxsDomq5yNMgw1o+AStlx/MjA=="
connection_string = f"DefaultEndpointsProtocol=https;AccountName={AZURE_STORAGE_ACCOUNT};AccountKey={AZURE_STORAGE_KEY};EndpointSuffix=core.windows.net"
blob_service_client = BlobServiceClient.from_connection_string(connection_string)

fs = AzureBlobFileSystem(
    account_name=AZURE_STORAGE_ACCOUNT,
    account_key=AZURE_STORAGE_KEY
)

In [ ]:
# Establish connection to preprocessed dataset
CONTAINER_NAME = "preprocessed"
container_client = blob_service_client.get_container_client(CONTAINER_NAME)

file_name = "preprocessed.csv"
data = load_csv_from_blob(file_name)
print(f"Loaded '{file_name}' with shape: {data.shape}")

Loaded 'preprocessed.csv' with shape: (53424, 44)

In [ ]:
print("Preprocessed Data:")
print(data.shape)
data.head()

Preprocessed Data:
(53424, 44)

,date and time,CYC_Clontarf James Larkin Rd,CYC_Clontarf Pebble Beach Carpark,CYC_Grove Road Totem,CYC_North Strand Rd N B,CYC_Richmond Street Cyclists 1 Merged,CYC_Richmond Street Cyclists 2 Merged,FTF_Aston Quay Merged,FTF_Capel St Mary St Merged,FTF_College St Dame St Merged,FTF_Dame St Merged,FTF_Dolier St Burgh Quay Merged,FTF_Grafton St Monsoon Merged,FTF_Grafton St Nassau St Suffolk St,FTF_Henry St Merged,FTF_Mary St Merged,FTF_Oconnell St Princes St North Merged,FTF_Talbot St Guineys Merged,FTF_Westmoreland St East Fleet St Merged,FTF_Westmoreland St West Merged,WTH_rain,WTH_temp,WTH_wetb,WTH_dewpt,WTH_vappr,WTH_rhum,WTH_msl,TEMP_year,TEMP_holiday,WTH_temp_3h,WTH_rain_int,WTH_dew_spread,WTH_prob_cond,WTH_severe,TEMP_hour_sin,TEMP_hour_cos,TEMP_day_sin,TEMP_day_cos,TEMP_month_sin,TEMP_month_cos,TEMP_weekend,TEMP_mor_peak,TEMP_eve_peak,TEMP_bus_hours
0,2019-01-01 00:00:00,0.0,0.0,12.0,16.0,0.0,0.0,0.0,238.0,0.0,0.0,0.0,140.0,0.0,597.0,163.0,1914.0,0.0,1670.0,1988.0,0.0,9.6,7.8,5.6,9.1,76.0,1035.1,2019,0,0.000000,0,4.0,0,0,0.000000,1.000000,0.781831,0.62349,0.5,0.866025,0,0,0,0
1,2019-01-01 01:00:00,0.0,0.0,17.0,14.0,0.0,0.0,0.0,173.0,0.0,0.0,0.0,215.0,0.0,359.0,102.0,885.0,0.0,767.0,1270.0,0.0,8.6,7.1,5.3,8.9,79.0,1035.1,2019,0,0.000000,0,3.3,0,0,0.258819,0.965926,0.781831,0.62349,0.5,0.866025,0,0,0,0
2,2019-01-01 02:00:00,0.0,0.0,18.0,9.0,0.0,0.0,0.0,121.0,0.0,0.0,0.0,210.0,0.0,317.0,63.0,984.0,0.0,642.0,1589.0,0.0,8.3,6.9,5.3,8.9,81.0,1034.9,2019,0,8.833333,0,3.0,0,0,0.500000,0.866025,0.781831,0.62349,0.5,0.866025,0,0,0,0
3,2019-01-01 03:00:00,0.0,0.0,18.0,15.0,0.0,0.0,0.0,174.0,0.0,0.0,0.0,204.0,0.0,313.0,59.0,935.0,0.0,582.0,1534.0,0.0,9.1,7.6,5.8,9.2,79.0,1035.5,2019,0,8.666667,0,3.3,0,0,0.707107,0.707107,0.781831,0.62349,0.5,0.866025,0,0,0,0
4,2019-01-01 04:00:00,0.0,0.0,12.0,8.0,0.0,0.0,0.0,82.0,0.0,0.0,0.0,88.0,0.0,172.0,46.0,390.0,0.0,143.0,610.0,0.0,9.2,7.7,5.9,9.3,79.0,1035.7,2019,0,8.866667,0,3.3,0,0,0.866025,0.500000,0.781831,0.62349,0.5,0.866025,0,0,0,0

### **2.1 DEFINE FEATURE CATEGORIES**

In [ ]:
data.head()

,date and time,CYC_Clontarf James Larkin Rd,CYC_Clontarf Pebble Beach Carpark,CYC_Grove Road Totem,CYC_North Strand Rd N B,CYC_Richmond Street Cyclists 1 Merged,CYC_Richmond Street Cyclists 2 Merged,FTF_Aston Quay Merged,FTF_Capel St Mary St Merged,FTF_College St Dame St Merged,FTF_Dame St Merged,FTF_Dolier St Burgh Quay Merged,FTF_Grafton St Monsoon Merged,FTF_Grafton St Nassau St Suffolk St,FTF_Henry St Merged,FTF_Mary St Merged,FTF_Oconnell St Princes St North Merged,FTF_Talbot St Guineys Merged,FTF_Westmoreland St East Fleet St Merged,FTF_Westmoreland St West Merged,WTH_rain,WTH_temp,WTH_wetb,WTH_dewpt,WTH_vappr,WTH_rhum,WTH_msl,TEMP_year,TEMP_holiday,WTH_temp_3h,WTH_rain_int,WTH_dew_spread,WTH_prob_cond,WTH_severe,TEMP_hour_sin,TEMP_hour_cos,TEMP_day_sin,TEMP_day_cos,TEMP_month_sin,TEMP_month_cos,TEMP_weekend,TEMP_mor_peak,TEMP_eve_peak,TEMP_bus_hours
0,2019-01-01 00:00:00,0.0,0.0,12.0,16.0,0.0,0.0,0.0,238.0,0.0,0.0,0.0,140.0,0.0,597.0,163.0,1914.0,0.0,1670.0,1988.0,0.0,9.6,7.8,5.6,9.1,76.0,1035.1,2019,0,0.000000,0,4.0,0,0,0.000000,1.000000,0.781831,0.62349,0.5,0.866025,0,0,0,0
1,2019-01-01 01:00:00,0.0,0.0,17.0,14.0,0.0,0.0,0.0,173.0,0.0,0.0,0.0,215.0,0.0,359.0,102.0,885.0,0.0,767.0,1270.0,0.0,8.6,7.1,5.3,8.9,79.0,1035.1,2019,0,0.000000,0,3.3,0,0,0.258819,0.965926,0.781831,0.62349,0.5,0.866025,0,0,0,0
2,2019-01-01 02:00:00,0.0,0.0,18.0,9.0,0.0,0.0,0.0,121.0,0.0,0.0,0.0,210.0,0.0,317.0,63.0,984.0,0.0,642.0,1589.0,0.0,8.3,6.9,5.3,8.9,81.0,1034.9,2019,0,8.833333,0,3.0,0,0,0.500000,0.866025,0.781831,0.62349,0.5,0.866025,0,0,0,0
3,2019-01-01 03:00:00,0.0,0.0,18.0,15.0,0.0,0.0,0.0,174.0,0.0,0.0,0.0,204.0,0.0,313.0,59.0,935.0,0.0,582.0,1534.0,0.0,9.1,7.6,5.8,9.2,79.0,1035.5,2019,0,8.666667,0,3.3,0,0,0.707107,0.707107,0.781831,0.62349,0.5,0.866025,0,0,0,0
4,2019-01-01 04:00:00,0.0,0.0,12.0,8.0,0.0,0.0,0.0,82.0,0.0,0.0,0.0,88.0,0.0,172.0,46.0,390.0,0.0,143.0,610.0,0.0,9.2,7.7,5.9,9.3,79.0,1035.7,2019,0,8.866667,0,3.3,0,0,0.866025,0.500000,0.781831,0.62349,0.5,0.866025,0,0,0,0

In [ ]:
# Interaction features created with weather features
interactionf = ["WTH_dew_spread", "WTH_prob_cond", "WTH_severe"]

# Using regex to get all temporal and weather prefix patterns
temp_pattern = re.compile(r"^TEMP_")
wth_patterb = re.compile(r"^WTH_")

# Using regex to get all temporal and weather features
temporalf = [col for col in data.columns if temp_pattern.match(col)]
weatherf = [col for col in data.columns if wth_patterb.match(col) and col not in interactionf]

In [ ]:
weatherf

['WTH_rain',
 'WTH_temp',
 'WTH_wetb',
 'WTH_dewpt',
 'WTH_vappr',
 'WTH_rhum',
 'WTH_msl',
 'WTH_temp_3h',
 'WTH_rain_int']

In [ ]:
temporalf

['TEMP_year',
 'TEMP_holiday',
 'TEMP_hour_sin',
 'TEMP_hour_cos',
 'TEMP_day_sin',
 'TEMP_day_cos',
 'TEMP_month_sin',
 'TEMP_month_cos',
 'TEMP_weekend',
 'TEMP_mor_peak',
 'TEMP_eve_peak',
 'TEMP_bus_hours']

In [ ]:
# Combine all features
fcolumns = weatherf + temporalf + interactionf

# Extract cycle and footfall targets
cycle_t = [col for col in data.columns if col.startswith("CYC_")]
footfall_t = [col for col in data.columns if col.startswith("FTF_")]
targets = cycle_t + footfall_t

# Prepare feature matrix
X = data[fcolumns].copy()
y = data[targets].copy()

# Handle missing values
X = X.ffill().bfill()
y = y.fillna(0)

print(f"Features shape: {X.shape}")
print(f"Targets shape: {y.shape}")
print(f"Feature columns: {len(fcolumns)}")

Features shape: (53424, 24)
Targets shape: (53424, 19)
Feature columns: 24

In [ ]:
targets

['CYC_Clontarf James Larkin Rd',
 'CYC_Clontarf Pebble Beach Carpark',
 'CYC_Grove Road Totem',
 'CYC_North Strand Rd N B',
 'CYC_Richmond Street Cyclists 1 Merged',
 'CYC_Richmond Street Cyclists 2 Merged',
 'FTF_Aston Quay Merged',
 'FTF_Capel St Mary St Merged',
 'FTF_College St Dame St Merged',
 'FTF_Dame St Merged',
 'FTF_Dolier St Burgh Quay Merged',
 'FTF_Grafton St Monsoon Merged',
 'FTF_Grafton St Nassau St Suffolk St',
 'FTF_Henry St Merged',
 'FTF_Mary St Merged',
 'FTF_Oconnell St Princes St North Merged',
 'FTF_Talbot St Guineys Merged',
 'FTF_Westmoreland St East Fleet St Merged',
 'FTF_Westmoreland St West Merged']

# **3. DEEP LEARNING MODELLING : LSTM**

### **3.1 DEFINE LSTM MODEL**

In [ ]:
# Creating LSTM sequences for multiple targets

def lstm_sequences(data, targets, features, seq_len=24):

    # Scaling features for all targets
    f_scaler = MinMaxScaler()
    f_data = f_scaler.fit_transform(data[features])

    # Dictionaries to store all results
    X_data = {}
    y_data = {}
    t_scalers = {}

    for t in targets:
        # Scaling each target
        y = data[t].values.reshape(-1, 1)
        t_scaler = MinMaxScaler()
        y_scaled = t_scaler.fit_transform(y)

        # Creating sequences
        X, y_seq = [], []
        for i in range(seq_len, len(f_data)):
            X.append(f_data[i-seq_len:i])
            y_seq.append(y_scaled[i])

        X_data[t] = np.array(X, dtype=np.float32)
        y_data[t] = np.array(y_seq, dtype=np.float32)
        t_scalers[t] = t_scaler

    return X_data, y_data, f_scaler, t_scalers


# Time series split

def ts_split(X, y, train_ratio=0.7, val_ratio=0.15):
    n_samples = len(X)
    train_end = int(n_samples * train_ratio)
    val_end = int(n_samples * (train_ratio + val_ratio))

    X_train = X[:train_end]
    y_train = y[:train_end]

    X_val = X[train_end:val_end]
    y_val = y[train_end:val_end]

    X_test = X[val_end:]
    y_test = y[val_end:]

    return X_train, X_val, X_test, y_train, y_val, y_test

# LSTM model

def build_lstm(input_shape):
    reg_strength = 1e-4  # Level 2 regularisation

    model = Sequential()
    model.add(Input(shape=input_shape))

    # First  LSTM layer
    model.add(LSTM(64, return_sequences=True,
                   kernel_regularizer=regularizers.l2(reg_strength)))
    model.add(Dropout(0.3))

    # Second LSTM layer
    model.add(LSTM(32, return_sequences=False,
                   kernel_regularizer=regularizers.l2(reg_strength)))
    model.add(Dropout(0.3))

    # Middle dense layer
    model.add(Dense(64, activation="relu",
                    kernel_regularizer=regularizers.l2(reg_strength)))
    model.add(Dropout(0.2))

    # Output
    model.add(Dense(1))

    model.compile(optimizer=Adam(learning_rate=0.001),
                  loss="mse",
                  metrics=["mae"])

    return model

# Callback: Early stopping if no improvement is done after 5 epochs
early_stop = EarlyStopping(monitor="val_loss", patience=5, restore_best_weights=True)

### **3.2 TRAIN MODEL**

In [ ]:
def train_lstm(target_name, X, y, strategy, callbacks=None):
    print(f"\nTraining model for: {target_name}")

    X_train, X_val, X_test, y_train, y_val, y_test = ts_split(X, y)

    print(f"Using strategy: {strategy.__class__.__name__}")

    with strategy.scope():
        model = build_lstm(input_shape=X_train.shape[1:])

        if callbacks is None:
            early_stopping = EarlyStopping(monitor="val_loss", patience=10, restore_best_weights=True)
            reduce_lr = ReduceLROnPlateau(monitor="val_loss", factor=0.5, patience=5, min_lr=1e-6)
            callbacks = [early_stopping, reduce_lr]

        history = model.fit(
            X_train, y_train,
            epochs=100,
            batch_size=1024,
            validation_data=(X_val, y_val),
            callbacks=callbacks,
            verbose=1
        )

    print(f"------Training completed for: {target_name}")
    return model, history, X_test, y_test

### **3.3 MODEL VALUATION METRICS**

In [ ]:
def evaluate_targets(model, X_test, y_test, target_scaler, target_name, target_idx, n_targets):
    print(f"\n----- Evaluating model for: {target_name} ({target_idx + 1}/{n_targets})")

    # Predictions
    y_pred = model.predict(X_test)

    # Verifying if y_test is in normalised scale
    if np.max(y_test) <= 1.0:
        y_true = target_scaler.inverse_transform(y_test.reshape(-1, 1))
    else:
        print("Warning: y_test seems to be scaled. Evaluation metrics could be inconsistent.")
        y_true = y_test.reshape(-1, 1)

    # Descale predictions
    y_pred = target_scaler.inverse_transform(y_pred)
    y_pred = np.round(y_pred).astype(int)

    # Evaluation metrics
    rmse = np.sqrt(np.mean((y_true - y_pred) ** 2))
    mae = np.mean(np.abs(y_true - y_pred))

    # Avoid division by zero in MAPE
    mask = y_true != 0
    if np.any(mask):
        mape = np.mean(np.abs((y_true[mask] - y_pred[mask]) / y_true[mask])) * 100
    else:
        mape = np.nan  # Unable to calculate MAPE

    r2 = r2_score(y_true, y_pred)

    # Results
    print("Evaluation Metrics:")
    print(f" -RMSE : {rmse:.2f}")
    print(f" -MAE  : {mae:.2f}")
    print(f" -MAPE : {mape:.2f}%")
    print(f" -R²   : {r2:.4f}")

    return {
        "RMSE": rmse,
        "MAE": mae,
        "MAPE": mape,
        "R2": r2
    }

### **3.4 APPLYING LSTM**

In [ ]:
# DATA FOR TARGETS

# Hours during the day
sequence_length = 24

X_lstm_dict, y_lstm_dict, feature_scaler_lstm, target_scaler_dict = lstm_sequences(
    pd.concat([X, y], axis=1),
    targets,
    fcolumns,
    sequence_length
)

strategy = tf.distribute.get_strategy()

In [ ]:
models = {}
histories = {}
results = {}
test_sets = {}

n_targets = len(targets)

for idx, target_name in enumerate(targets, 1):
    print(f"\n--- Processing target {idx} out of {n_targets}: {target_name}")

    # Get specific data for target
    X_data = X_lstm_dict[target_name]
    y_data = y_lstm_dict[target_name]

    # Training model for target
    model, history, X_test, y_test = train_lstm(
        target_name,
        X_data,
        y_data,
        strategy,
        callbacks=[early_stop]
    )

    # Save model and historical
    models[target_name] = model
    histories[target_name] = history

    # Save test sets for further evaluation
    test_sets[target_name] = (X_test, y_test)

    # Target scaler for predictions and real values descalation
    target_scaler = target_scaler_dict[target_name]

    # Evaluate the model
    metrics = evaluate_targets(
        model,
        X_test,
        y_test,
        target_scaler,
        target_name,
        idx,
        n_targets
    )

    results[target_name] = metrics

print("\nTraining and evaluation completed for all targets.")

--- Processing target 1 out of 19: CYC_Clontarf James Larkin Rd

Training model for: CYC_Clontarf James Larkin Rd
Using strategy: _DefaultDistributionStrategy
Epoch 1/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - loss: 0.0249 - mae: 0.0651 - val_loss: 0.0221 - val_mae: 0.0844
Epoch 2/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0165 - mae: 0.0413 - val_loss: 0.0182 - val_mae: 0.0793
Epoch 3/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0126 - mae: 0.0359 - val_loss: 0.0192 - val_mae: 0.0925
Epoch 4/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0101 - mae: 0.0332 - val_loss: 0.0154 - val_mae: 0.0812
Epoch 5/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0084 - mae: 0.0314 - val_loss: 0.0118 - val_mae: 0.0674
Epoch 6/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0072 - mae: 0.0296 - val_loss: 0.0092 - val_mae: 0.0569
Epoch 7/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0063 - mae: 0.0282 - val_loss: 0.0059 - val_mae: 0.0356
Epoch 8/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0054 - mae: 0.0259 - val_loss: 0.0060 - val_mae: 0.0363
Epoch 9/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0046 - mae: 0.0224 - val_loss: 0.0058 - val_mae: 0.0353
Epoch 10/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0042 - mae: 0.0212 - val_loss: 0.0047 - val_mae: 0.0314
Epoch 11/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0038 - mae: 0.0197 - val_loss: 0.0043 - val_mae: 0.0295
Epoch 12/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0034 - mae: 0.0186 - val_loss: 0.0039 - val_mae: 0.0283
Epoch 13/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0032 - mae: 0.0180 - val_loss: 0.0037 - val_mae: 0.0279
Epoch 14/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0029 - mae: 0.0175 - val_loss: 0.0035 - val_mae: 0.0279
Epoch 15/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0028 - mae: 0.0174 - val_loss: 0.0033 - val_mae: 0.0274
Epoch 16/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0026 - mae: 0.0168 - val_loss: 0.0031 - val_mae: 0.0268
Epoch 17/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0026 - mae: 0.0178 - val_loss: 0.0030 - val_mae: 0.0272
Epoch 18/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0027 - mae: 0.0183 - val_loss: 0.0030 - val_mae: 0.0264
Epoch 19/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0023 - mae: 0.0165 - val_loss: 0.0028 - val_mae: 0.0257
Epoch 20/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0022 - mae: 0.0162 - val_loss: 0.0028 - val_mae: 0.0261
Epoch 21/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0020 - mae: 0.0154 - val_loss: 0.0025 - val_mae: 0.0247
Epoch 22/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0020 - mae: 0.0156 - val_loss: 0.0026 - val_mae: 0.0252
Epoch 23/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0019 - mae: 0.0152 - val_loss: 0.0025 - val_mae: 0.0251
Epoch 24/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0020 - mae: 0.0158 - val_loss: 0.0025 - val_mae: 0.0256
Epoch 25/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0019 - mae: 0.0156 - val_loss: 0.0023 - val_mae: 0.0248
Epoch 26/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0018 - mae: 0.0154 - val_loss: 0.0024 - val_mae: 0.0254
Epoch 27/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0018 - mae: 0.0152 - val_loss: 0.0024 - val_mae: 0.0251
Epoch 28/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0018 - mae: 0.0155 - val_loss: 0.0025 - val_mae: 0.0265
Epoch 29/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0030 - mae: 0.0216 - val_loss: 0.0024 - val_mae: 0.0260
Epoch 30/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0018 - mae: 0.0160 - val_loss: 0.0024 - val_mae: 0.0256
------Training completed for: CYC_Clontarf James Larkin Rd

----- Evaluating model for: CYC_Clontarf James Larkin Rd (2/19)
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step
Evaluation Metrics:
 -RMSE : 20.21
 -MAE  : 12.47
 -MAPE : 60.85%
 -R²   : 0.7240

--- Processing target 2 out of 19: CYC_Clontarf Pebble Beach Carpark

Training model for: CYC_Clontarf Pebble Beach Carpark
Using strategy: _DefaultDistributionStrategy
Epoch 1/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - loss: 0.0276 - mae: 0.0758 - val_loss: 0.0194 - val_mae: 0.0576
Epoch 2/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0177 - mae: 0.0449 - val_loss: 0.0167 - val_mae: 0.0643
Epoch 3/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0140 - mae: 0.0386 - val_loss: 0.0132 - val_mae: 0.0545
Epoch 4/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0114 - mae: 0.0348 - val_loss: 0.0145 - val_mae: 0.0712
Epoch 5/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0097 - mae: 0.0329 - val_loss: 0.0131 - val_mae: 0.0675
Epoch 6/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0084 - mae: 0.0307 - val_loss: 0.0102 - val_mae: 0.0551
Epoch 7/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0075 - mae: 0.0293 - val_loss: 0.0094 - val_mae: 0.0520
Epoch 8/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0067 - mae: 0.0280 - val_loss: 0.0067 - val_mae: 0.0360
Epoch 9/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0058 - mae: 0.0256 - val_loss: 0.0075 - val_mae: 0.0383
Epoch 10/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0050 - mae: 0.0227 - val_loss: 0.0062 - val_mae: 0.0341
Epoch 11/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0046 - mae: 0.0208 - val_loss: 0.0058 - val_mae: 0.0331
Epoch 12/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0041 - mae: 0.0191 - val_loss: 0.0054 - val_mae: 0.0326
Epoch 13/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0038 - mae: 0.0184 - val_loss: 0.0046 - val_mae: 0.0306
Epoch 14/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0035 - mae: 0.0175 - val_loss: 0.0043 - val_mae: 0.0307
Epoch 15/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0035 - mae: 0.0181 - val_loss: 0.0044 - val_mae: 0.0301
Epoch 16/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0031 - mae: 0.0166 - val_loss: 0.0041 - val_mae: 0.0290
Epoch 17/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0029 - mae: 0.0161 - val_loss: 0.0038 - val_mae: 0.0282
Epoch 18/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0028 - mae: 0.0162 - val_loss: 0.0038 - val_mae: 0.0292
Epoch 19/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0026 - mae: 0.0160 - val_loss: 0.0036 - val_mae: 0.0283
Epoch 20/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0026 - mae: 0.0159 - val_loss: 0.0034 - val_mae: 0.0276
Epoch 21/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0025 - mae: 0.0161 - val_loss: 0.0035 - val_mae: 0.0284
Epoch 22/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0027 - mae: 0.0169 - val_loss: 0.0035 - val_mae: 0.0288
Epoch 23/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0024 - mae: 0.0158 - val_loss: 0.0036 - val_mae: 0.0297
Epoch 24/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0021 - mae: 0.0150 - val_loss: 0.0031 - val_mae: 0.0274
Epoch 25/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0021 - mae: 0.0147 - val_loss: 0.0031 - val_mae: 0.0275
Epoch 26/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0020 - mae: 0.0147 - val_loss: 0.0031 - val_mae: 0.0281
Epoch 27/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0020 - mae: 0.0149 - val_loss: 0.0032 - val_mae: 0.0284
Epoch 28/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0019 - mae: 0.0148 - val_loss: 0.0031 - val_mae: 0.0282
Epoch 29/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0018 - mae: 0.0147 - val_loss: 0.0027 - val_mae: 0.0269
Epoch 30/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0018 - mae: 0.0147 - val_loss: 0.0030 - val_mae: 0.0283
Epoch 31/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0018 - mae: 0.0146 - val_loss: 0.0027 - val_mae: 0.0272
Epoch 32/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0017 - mae: 0.0147 - val_loss: 0.0026 - val_mae: 0.0267
Epoch 33/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0017 - mae: 0.0146 - val_loss: 0.0026 - val_mae: 0.0269
Epoch 34/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0016 - mae: 0.0145 - val_loss: 0.0025 - val_mae: 0.0269
Epoch 35/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0017 - mae: 0.0147 - val_loss: 0.0027 - val_mae: 0.0274
Epoch 36/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0016 - mae: 0.0142 - val_loss: 0.0025 - val_mae: 0.0267
Epoch 37/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0015 - mae: 0.0141 - val_loss: 0.0024 - val_mae: 0.0264
Epoch 38/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0015 - mae: 0.0142 - val_loss: 0.0024 - val_mae: 0.0272
Epoch 39/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0015 - mae: 0.0145 - val_loss: 0.0024 - val_mae: 0.0276
Epoch 40/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0015 - mae: 0.0150 - val_loss: 0.0026 - val_mae: 0.0277
Epoch 41/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0015 - mae: 0.0145 - val_loss: 0.0023 - val_mae: 0.0261
Epoch 42/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0015 - mae: 0.0146 - val_loss: 0.0025 - val_mae: 0.0294
Epoch 43/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0016 - mae: 0.0154 - val_loss: 0.0024 - val_mae: 0.0267
Epoch 44/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0014 - mae: 0.0141 - val_loss: 0.0024 - val_mae: 0.0268
Epoch 45/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0015 - mae: 0.0144 - val_loss: 0.0023 - val_mae: 0.0272
Epoch 46/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0015 - mae: 0.0146 - val_loss: 0.0025 - val_mae: 0.0270
Epoch 47/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0015 - mae: 0.0147 - val_loss: 0.0022 - val_mae: 0.0263
Epoch 48/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0015 - mae: 0.0148 - val_loss: 0.0023 - val_mae: 0.0260
Epoch 49/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0013 - mae: 0.0139 - val_loss: 0.0022 - val_mae: 0.0261
Epoch 50/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0014 - mae: 0.0139 - val_loss: 0.0024 - val_mae: 0.0270
Epoch 51/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0136 - val_loss: 0.0023 - val_mae: 0.0260
Epoch 52/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0141 - val_loss: 0.0023 - val_mae: 0.0263
------Training completed for: CYC_Clontarf Pebble Beach Carpark

----- Evaluating model for: CYC_Clontarf Pebble Beach Carpark (3/19)
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step
Evaluation Metrics:
 -RMSE : 25.80
 -MAE  : 16.43
 -MAPE : 75.49%
 -R²   : 0.7786

--- Processing target 3 out of 19: CYC_Grove Road Totem

Training model for: CYC_Grove Road Totem
Using strategy: _DefaultDistributionStrategy
Epoch 1/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 3s 23ms/step - loss: 0.0356 - mae: 0.0960 - val_loss: 0.0229 - val_mae: 0.0548
Epoch 2/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0233 - mae: 0.0597 - val_loss: 0.0182 - val_mae: 0.0420
Epoch 3/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0191 - mae: 0.0532 - val_loss: 0.0152 - val_mae: 0.0375
Epoch 4/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0163 - mae: 0.0503 - val_loss: 0.0137 - val_mae: 0.0358
Epoch 5/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0143 - mae: 0.0475 - val_loss: 0.0124 - val_mae: 0.0355
Epoch 6/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0127 - mae: 0.0449 - val_loss: 0.0114 - val_mae: 0.0355
Epoch 7/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0114 - mae: 0.0428 - val_loss: 0.0103 - val_mae: 0.0348
Epoch 8/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0103 - mae: 0.0410 - val_loss: 0.0093 - val_mae: 0.0345
Epoch 9/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0096 - mae: 0.0396 - val_loss: 0.0094 - val_mae: 0.0357
Epoch 10/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0088 - mae: 0.0378 - val_loss: 0.0080 - val_mae: 0.0341
Epoch 11/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0083 - mae: 0.0368 - val_loss: 0.0071 - val_mae: 0.0330
Epoch 12/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0078 - mae: 0.0361 - val_loss: 0.0064 - val_mae: 0.0317
Epoch 13/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0072 - mae: 0.0351 - val_loss: 0.0076 - val_mae: 0.0498
Epoch 14/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0068 - mae: 0.0344 - val_loss: 0.0092 - val_mae: 0.0592
Epoch 15/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0064 - mae: 0.0335 - val_loss: 0.0082 - val_mae: 0.0537
Epoch 16/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0059 - mae: 0.0319 - val_loss: 0.0069 - val_mae: 0.0452
Epoch 17/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0057 - mae: 0.0316 - val_loss: 0.0057 - val_mae: 0.0393
Epoch 18/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0310 - val_loss: 0.0059 - val_mae: 0.0406
Epoch 19/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0052 - mae: 0.0306 - val_loss: 0.0071 - val_mae: 0.0485
Epoch 20/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0049 - mae: 0.0298 - val_loss: 0.0061 - val_mae: 0.0422
Epoch 21/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0048 - mae: 0.0296 - val_loss: 0.0065 - val_mae: 0.0443
Epoch 22/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0047 - mae: 0.0293 - val_loss: 0.0061 - val_mae: 0.0426
------Training completed for: CYC_Grove Road Totem

----- Evaluating model for: CYC_Grove Road Totem (4/19)
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step
Evaluation Metrics:
 -RMSE : 118.57
 -MAE  : 90.92
 -MAPE : 392.73%
 -R²   : 0.0161

--- Processing target 4 out of 19: CYC_North Strand Rd N B

Training model for: CYC_North Strand Rd N B
Using strategy: _DefaultDistributionStrategy
Epoch 1/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 3s 23ms/step - loss: 0.0276 - mae: 0.0714 - val_loss: 0.0150 - val_mae: 0.0282
Epoch 2/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0169 - mae: 0.0419 - val_loss: 0.0108 - val_mae: 0.0289
Epoch 3/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0129 - mae: 0.0374 - val_loss: 0.0086 - val_mae: 0.0281
Epoch 4/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0104 - mae: 0.0348 - val_loss: 0.0069 - val_mae: 0.0271
Epoch 5/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0087 - mae: 0.0335 - val_loss: 0.0061 - val_mae: 0.0309
Epoch 6/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0074 - mae: 0.0322 - val_loss: 0.0051 - val_mae: 0.0229
Epoch 7/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0066 - mae: 0.0313 - val_loss: 0.0044 - val_mae: 0.0202
Epoch 8/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0061 - mae: 0.0308 - val_loss: 0.0041 - val_mae: 0.0214
Epoch 9/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0299 - val_loss: 0.0036 - val_mae: 0.0191
Epoch 10/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0051 - mae: 0.0293 - val_loss: 0.0035 - val_mae: 0.0203
Epoch 11/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0048 - mae: 0.0289 - val_loss: 0.0030 - val_mae: 0.0193
Epoch 12/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0045 - mae: 0.0282 - val_loss: 0.0029 - val_mae: 0.0221
Epoch 13/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0042 - mae: 0.0277 - val_loss: 0.0026 - val_mae: 0.0145
Epoch 14/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0039 - mae: 0.0267 - val_loss: 0.0017 - val_mae: 0.0062
Epoch 15/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0037 - mae: 0.0258 - val_loss: 0.0016 - val_mae: 0.0042
Epoch 16/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0033 - mae: 0.0242 - val_loss: 0.0015 - val_mae: 0.0046
Epoch 17/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0032 - mae: 0.0241 - val_loss: 0.0013 - val_mae: 0.0039
Epoch 18/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0030 - mae: 0.0235 - val_loss: 0.0013 - val_mae: 0.0047
Epoch 19/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0029 - mae: 0.0232 - val_loss: 0.0013 - val_mae: 0.0053
Epoch 20/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0027 - mae: 0.0228 - val_loss: 0.0012 - val_mae: 0.0046
Epoch 21/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0026 - mae: 0.0225 - val_loss: 0.0011 - val_mae: 0.0051
Epoch 22/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0025 - mae: 0.0227 - val_loss: 9.2984e-04 - val_mae: 0.0041
Epoch 23/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0025 - mae: 0.0226 - val_loss: 8.9748e-04 - val_mae: 0.0037
Epoch 24/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0024 - mae: 0.0227 - val_loss: 8.4058e-04 - val_mae: 0.0032
Epoch 25/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0024 - mae: 0.0223 - val_loss: 8.8229e-04 - val_mae: 0.0042
Epoch 26/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0023 - mae: 0.0219 - val_loss: 7.8374e-04 - val_mae: 0.0045
Epoch 27/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0023 - mae: 0.0222 - val_loss: 8.7186e-04 - val_mae: 0.0059
Epoch 28/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0022 - mae: 0.0221 - val_loss: 9.5027e-04 - val_mae: 0.0082
Epoch 29/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0021 - mae: 0.0220 - val_loss: 6.5519e-04 - val_mae: 0.0033
Epoch 30/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0021 - mae: 0.0217 - val_loss: 9.5240e-04 - val_mae: 0.0058
Epoch 31/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0021 - mae: 0.0221 - val_loss: 0.0014 - val_mae: 0.0078
Epoch 32/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0223 - val_loss: 8.9450e-04 - val_mae: 0.0088
Epoch 33/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0020 - mae: 0.0215 - val_loss: 6.8412e-04 - val_mae: 0.0048
Epoch 34/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0020 - mae: 0.0219 - val_loss: 0.0011 - val_mae: 0.0064
------Training completed for: CYC_North Strand Rd N B

----- Evaluating model for: CYC_North Strand Rd N B (5/19)
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step
Evaluation Metrics:
 -RMSE : 1.18
 -MAE  : 0.92
 -MAPE : nan%
 -R²   : 0.0000

--- Processing target 5 out of 19: CYC_Richmond Street Cyclists 1 Merged

Training model for: CYC_Richmond Street Cyclists 1 Merged
Using strategy: _DefaultDistributionStrategy
Epoch 1/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 3s 22ms/step - loss: 0.0347 - mae: 0.0974 - val_loss: 0.0360 - val_mae: 0.1195
Epoch 2/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0210 - mae: 0.0603 - val_loss: 0.0360 - val_mae: 0.1283
Epoch 3/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0172 - mae: 0.0542 - val_loss: 0.0308 - val_mae: 0.1138
Epoch 4/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0142 - mae: 0.0500 - val_loss: 0.0223 - val_mae: 0.0807
Epoch 5/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0116 - mae: 0.0443 - val_loss: 0.0204 - val_mae: 0.0682
Epoch 6/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0096 - mae: 0.0374 - val_loss: 0.0189 - val_mae: 0.0655
Epoch 7/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0085 - mae: 0.0348 - val_loss: 0.0176 - val_mae: 0.0641
Epoch 8/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0076 - mae: 0.0332 - val_loss: 0.0166 - val_mae: 0.0613
Epoch 9/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0070 - mae: 0.0322 - val_loss: 0.0164 - val_mae: 0.0611
Epoch 10/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0065 - mae: 0.0312 - val_loss: 0.0158 - val_mae: 0.0608
Epoch 11/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0060 - mae: 0.0303 - val_loss: 0.0153 - val_mae: 0.0595
Epoch 12/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0056 - mae: 0.0294 - val_loss: 0.0150 - val_mae: 0.0597
Epoch 13/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0054 - mae: 0.0295 - val_loss: 0.0142 - val_mae: 0.0588
Epoch 14/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0052 - mae: 0.0290 - val_loss: 0.0136 - val_mae: 0.0575
Epoch 15/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0048 - mae: 0.0281 - val_loss: 0.0135 - val_mae: 0.0572
Epoch 16/100

### **3.5 MODEL SUMMARY**

In [ ]:
for target_name, model in models.items():
    print(f"\n--- Summary for target: {target_name}")
    model.summary()

--- Summary for target: CYC_Clontarf James Larkin Rd

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 24, 64)         │        22,784 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 112,137 (438.05 KB)

 Trainable params: 37,377 (146.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 74,760 (292.04 KB)

--- Summary for target: CYC_Clontarf Pebble Beach Carpark

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_2 (LSTM)                   │ (None, 24, 64)         │        22,784 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_3 (LSTM)                   │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 112,137 (438.05 KB)

 Trainable params: 37,377 (146.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 74,760 (292.04 KB)

--- Summary for target: CYC_Grove Road Totem

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_4 (LSTM)                   │ (None, 24, 64)         │        22,784 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_6 (Dropout)             │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_5 (LSTM)                   │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_7 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_8 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 112,137 (438.05 KB)

 Trainable params: 37,377 (146.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 74,760 (292.04 KB)

--- Summary for target: CYC_North Strand Rd N B

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_6 (LSTM)                   │ (None, 24, 64)         │        22,784 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_9 (Dropout)             │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_7 (LSTM)                   │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_10 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_11 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 112,137 (438.05 KB)

 Trainable params: 37,377 (146.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 74,760 (292.04 KB)

--- Summary for target: CYC_Richmond Street Cyclists 1 Merged

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_8 (LSTM)                   │ (None, 24, 64)         │        22,784 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_12 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_9 (LSTM)                   │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_13 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_14 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 112,137 (438.05 KB)

 Trainable params: 37,377 (146.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 74,760 (292.04 KB)

--- Summary for target: CYC_Richmond Street Cyclists 2 Merged

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_10 (LSTM)                  │ (None, 24, 64)         │        22,784 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_15 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_11 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_16 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_17 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 112,137 (438.05 KB)

 Trainable params: 37,377 (146.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 74,760 (292.04 KB)

--- Summary for target: FTF_Aston Quay Merged

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_12 (LSTM)                  │ (None, 24, 64)         │        22,784 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_18 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_13 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_19 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_20 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 112,137 (438.05 KB)

 Trainable params: 37,377 (146.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 74,760 (292.04 KB)

--- Summary for target: FTF_Capel St Mary St Merged

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_14 (LSTM)                  │ (None, 24, 64)         │        22,784 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_21 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_15 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_22 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_23 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 112,137 (438.05 KB)

 Trainable params: 37,377 (146.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 74,760 (292.04 KB)

--- Summary for target: FTF_College St Dame St Merged

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_16 (LSTM)                  │ (None, 24, 64)         │        22,784 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_24 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_17 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_25 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_16 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_26 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 112,137 (438.05 KB)

 Trainable params: 37,377 (146.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 74,760 (292.04 KB)

--- Summary for target: FTF_Dame St Merged

Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_18 (LSTM)                  │ (None, 24, 64)         │        22,784 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_27 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_19 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_28 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_18 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_29 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_19 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 112,137 (438.05 KB)

 Trainable params: 37,377 (146.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 74,760 (292.04 KB)

--- Summary for target: FTF_Dolier St Burgh Quay Merged

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_20 (LSTM)                  │ (None, 24, 64)         │        22,784 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_30 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_21 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_31 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_20 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_32 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_21 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 112,137 (438.05 KB)

 Trainable params: 37,377 (146.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 74,760 (292.04 KB)

--- Summary for target: FTF_Grafton St Monsoon Merged

Model: "sequential_11"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_22 (LSTM)                  │ (None, 24, 64)         │        22,784 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_33 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_23 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_34 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_22 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_35 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_23 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 112,137 (438.05 KB)

 Trainable params: 37,377 (146.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 74,760 (292.04 KB)

--- Summary for target: FTF_Grafton St Nassau St Suffolk St

Model: "sequential_12"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_24 (LSTM)                  │ (None, 24, 64)         │        22,784 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_36 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_25 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_37 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_24 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_38 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_25 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 112,137 (438.05 KB)

 Trainable params: 37,377 (146.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 74,760 (292.04 KB)

--- Summary for target: FTF_Henry St Merged

Model: "sequential_13"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_26 (LSTM)                  │ (None, 24, 64)         │        22,784 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_39 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_27 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_40 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_26 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_41 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_27 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 112,137 (438.05 KB)

 Trainable params: 37,377 (146.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 74,760 (292.04 KB)

--- Summary for target: FTF_Mary St Merged

Model: "sequential_14"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_28 (LSTM)                  │ (None, 24, 64)         │        22,784 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_42 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_29 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_43 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_28 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_44 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_29 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 112,137 (438.05 KB)

 Trainable params: 37,377 (146.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 74,760 (292.04 KB)

--- Summary for target: FTF_Oconnell St Princes St North Merged

Model: "sequential_15"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_30 (LSTM)                  │ (None, 24, 64)         │        22,784 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_45 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_31 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_46 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_30 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_47 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_31 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 112,137 (438.05 KB)

 Trainable params: 37,377 (146.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 74,760 (292.04 KB)

--- Summary for target: FTF_Talbot St Guineys Merged

Model: "sequential_16"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_32 (LSTM)                  │ (None, 24, 64)         │        22,784 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_48 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_33 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_49 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_32 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_50 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_33 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 112,137 (438.05 KB)

 Trainable params: 37,377 (146.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 74,760 (292.04 KB)

--- Summary for target: FTF_Westmoreland St East Fleet St Merged

Model: "sequential_17"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_34 (LSTM)                  │ (None, 24, 64)         │        22,784 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_51 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_35 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_52 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_34 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_53 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_35 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 112,137 (438.05 KB)

 Trainable params: 37,377 (146.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 74,760 (292.04 KB)

--- Summary for target: FTF_Westmoreland St West Merged

Model: "sequential_18"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_36 (LSTM)                  │ (None, 24, 64)         │        22,784 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_54 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_37 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_55 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_36 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_56 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_37 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 112,137 (438.05 KB)

 Trainable params: 37,377 (146.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 74,760 (292.04 KB)

### **3.6 RESULTS**

In [ ]:
results= pd.DataFrame.from_dict(results, orient="index")
results.index.name = "Target"
results = results.reset_index()
print("\nSummary of results with LSTM:")
results

Summary of results with LSTM:

,Target,RMSE,MAE,MAPE,R2
0,CYC_Clontarf James Larkin Rd,20.205270,12.467665,60.847362,0.723985
1,CYC_Clontarf Pebble Beach Carpark,25.795065,16.428589,75.494677,0.778577
2,CYC_Grove Road Totem,118.567539,90.920974,392.726553,0.016082
3,CYC_North Strand Rd N B,1.179888,0.918477,NaN,0.000000
4,CYC_Richmond Street Cyclists 1 Merged,40.126031,24.078402,81.163775,0.244495
5,CYC_Richmond Street Cyclists 2 Merged,24.611752,15.119850,46.220968,0.665332
6,FTF_Aston Quay Merged,2198.047077,2059.324844,414.334514,-2.124199
7,FTF_Capel St Mary St Merged,1825.593882,1751.740324,972.582342,-8.417004
8,FTF_College St Dame St Merged,348.005419,283.922347,233.610354,0.321135
9,FTF_Dame St Merged,306.287914,232.082272,270.478224,0.080669
10,FTF_Dolier St Burgh Quay Merged,1538.932464,1466.169288,1382.453900,-26.652592
11,FTF_Grafton St Monsoon Merged,716.961121,561.138826,253.269632,0.574542
12,FTF_Grafton St Nassau St Suffolk St,140.373535,102.356180,224.771504,0.621813
13,FTF_Henry St Merged,8592.196098,6524.537078,6161.614569,-27.675846
14,FTF_Mary St Merged,255.076038,177.556679,156.732111,0.712696
15,FTF_Oconnell St Princes St North Merged,850.542180,722.358801,119.491006,-1.229043
16,FTF_Talbot St Guineys Merged,2453.231715,2383.543071,6496.936866,-63.495949
17,FTF_Westmoreland St East Fleet St Merged,1744.316966,1691.871411,NaN,0.000000
18,FTF_Westmoreland St West Merged,358.671070,252.518851,120.044395,0.605144

### **3.7 PREDICTIONS**

In [ ]:
predictions = {}

for target_name in targets:
    print(f"\nPredicting values for: {target_name}")

    # Test data and targets
    X_test, y_test = test_sets[target_name]
    target_scaler = target_scaler_dict[target_name]

    # Scaled predictions
    y_pred_scaled = models[target_name].predict(X_test)

    # Descale predictions to original values
    y_pred = target_scaler.inverse_transform(y_pred_scaled)
    y_true = target_scaler.inverse_transform(y_test.reshape(-1, 1))

    # DATE AND TIME FROM TEST SET

    # Length used in ltsm sequences
    seq_len = sequence_length

    # Index from start of test set to match the target
    n_total = len(y_lstm_dict[target_name])
    n_train = int(n_total * 0.7)
    n_val   = int(n_total * 0.15)
    start_test_idx = seq_len + n_train + n_val

    datest = data["date and time"].iloc[start_test_idx:].reset_index(drop=True)

    # New DataFrame with values needed for comparison
    predsDataFrame = pd.DataFrame({
        "date and time": datest,
        "Real": y_true.flatten(),
        "LSTM_nocoords": y_pred.flatten()
    })

    # Round predictions and avoid negative values
    predsDataFrame["LSTM_nocoords"] = np.round(predsDataFrame["LSTM_nocoords"]).astype(int)
    predsDataFrame["LSTM_nocoords"] = predsDataFrame["LSTM_nocoords"].clip(lower=0)

    predictions[target_name] = predsDataFrame
    print(predsDataFrame.head())

# DataFrame for all predictions
allpreds = pd.concat(
    [dataframe.assign(Target=target) for target, dataframe in predictions.items()],
    ignore_index=True
)

Predicting values for: CYC_Clontarf James Larkin Rd
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
         date and time  Real  LSTM_nocoords
0  2024-03-07 06:00:00  20.0             25
1  2024-03-07 07:00:00  49.0             43
2  2024-03-07 08:00:00  70.0             52
3  2024-03-07 09:00:00  51.0             51
4  2024-03-07 10:00:00  31.0             43

Predicting values for: CYC_Clontarf Pebble Beach Carpark
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
         date and time   Real  LSTM_nocoords
0  2024-03-07 06:00:00   26.0             44
1  2024-03-07 07:00:00   75.0             67
2  2024-03-07 08:00:00  105.0             75
3  2024-03-07 09:00:00   75.0             66
4  2024-03-07 10:00:00   33.0             53

Predicting values for: CYC_Grove Road Totem
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
         date and time   Real  LSTM_nocoords
0  2024-03-07 06:00:00  125.0            337
1  2024-03-07 07:00:00  309.0            485
2  2024-03-07 08:00:00  607.0            488
3  2024-03-07 09:00:00  247.0            312
4  2024-03-07 10:00:00   94.0            126

Predicting values for: CYC_North Strand Rd N B
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
         date and time  Real  LSTM_nocoords
0  2024-03-07 06:00:00   0.0              0
1  2024-03-07 07:00:00   0.0              0
2  2024-03-07 08:00:00   0.0              1
3  2024-03-07 09:00:00   0.0              1
4  2024-03-07 10:00:00   0.0              1

Predicting values for: CYC_Richmond Street Cyclists 1 Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
         date and time   Real  LSTM_nocoords
0  2024-03-07 06:00:00   21.0             45
1  2024-03-07 07:00:00   88.0            106
2  2024-03-07 08:00:00  244.0            152
3  2024-03-07 09:00:00  135.0            168
4  2024-03-07 10:00:00   75.0            156

Predicting values for: CYC_Richmond Street Cyclists 2 Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
         date and time  Real  LSTM_nocoords
0  2024-03-07 06:00:00  12.0              5
1  2024-03-07 07:00:00  38.0              9
2  2024-03-07 08:00:00  53.0             17
3  2024-03-07 09:00:00  37.0             21
4  2024-03-07 10:00:00  19.0             23

Predicting values for: FTF_Aston Quay Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
         date and time    Real  LSTM_nocoords
0  2024-03-07 06:00:00  1524.0           3444
1  2024-03-07 07:00:00  2191.0           4164
2  2024-03-07 08:00:00  4623.0           4332
3  2024-03-07 09:00:00  3941.0           4460
4  2024-03-07 10:00:00  2430.0           4468

Predicting values for: FTF_Capel St Mary St Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
         date and time         Real  LSTM_nocoords
0  2024-03-07 06:00:00   347.999969           1713
1  2024-03-07 07:00:00   305.000000           1781
2  2024-03-07 08:00:00  1026.000000           1905
3  2024-03-07 09:00:00  1098.000000           2064
4  2024-03-07 10:00:00  1721.000000           2280

Predicting values for: FTF_College St Dame St Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
         date and time         Real  LSTM_nocoords
0  2024-03-07 06:00:00   250.000000            266
1  2024-03-07 07:00:00   533.000000            653
2  2024-03-07 08:00:00  1243.000000           1066
3  2024-03-07 09:00:00   966.000061           1194
4  2024-03-07 10:00:00   809.000000           1180

Predicting values for: FTF_Dame St Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
         date and time        Real  LSTM_nocoords
0  2024-03-07 06:00:00  293.000000            211
1  2024-03-07 07:00:00  480.000000            276
2  2024-03-07 08:00:00  663.000000            356
3  2024-03-07 09:00:00  702.000061            449
4  2024-03-07 10:00:00  596.000000            530

Predicting values for: FTF_Dolier St Burgh Quay Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
         date and time        Real  LSTM_nocoords
0  2024-03-07 06:00:00  291.000000           1311
1  2024-03-07 07:00:00  493.999969           1619
2  2024-03-07 08:00:00  822.999939           1850
3  2024-03-07 09:00:00  752.000061           2005
4  2024-03-07 10:00:00  535.000000           2088

Predicting values for: FTF_Grafton St Monsoon Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
         date and time         Real  LSTM_nocoords
0  2024-03-07 06:00:00  1866.999878           1659
1  2024-03-07 07:00:00  1909.000000           2142
2  2024-03-07 08:00:00  1718.000000           2606
3  2024-03-07 09:00:00  2174.000000           3026
4  2024-03-07 10:00:00  2111.000000           3394

Predicting values for: FTF_Grafton St Nassau St Suffolk St
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
         date and time   Real  LSTM_nocoords
0  2024-03-07 06:00:00   76.0            144
1  2024-03-07 07:00:00  162.0            218
2  2024-03-07 08:00:00  469.0            292
3  2024-03-07 09:00:00  330.0            352
4  2024-03-07 10:00:00  273.0            394

Predicting values for: FTF_Henry St Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
         date and time    Real  LSTM_nocoords
0  2024-03-07 06:00:00   458.0           1222
1  2024-03-07 07:00:00   925.0           2084
2  2024-03-07 08:00:00  2353.0           3188
3  2024-03-07 09:00:00  3062.0           4844
4  2024-03-07 10:00:00  4369.0           6688

Predicting values for: FTF_Mary St Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
         date and time        Real  LSTM_nocoords
0  2024-03-07 06:00:00   58.999996            139
1  2024-03-07 07:00:00   87.000000            197
2  2024-03-07 08:00:00  286.000000            277
3  2024-03-07 09:00:00  334.000000            395
4  2024-03-07 10:00:00  918.000000            526

Predicting values for: FTF_Oconnell St Princes St North Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
         date and time    Real  LSTM_nocoords
0  2024-03-07 06:00:00   366.0            412
1  2024-03-07 07:00:00   598.0            534
2  2024-03-07 08:00:00  1050.0            704
3  2024-03-07 09:00:00   760.0            857
4  2024-03-07 10:00:00   720.0            998

Predicting values for: FTF_Talbot St Guineys Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
         date and time  Real  LSTM_nocoords
0  2024-03-07 06:00:00   0.0           2488
1  2024-03-07 07:00:00   0.0           2500
2  2024-03-07 08:00:00   0.0           2560
3  2024-03-07 09:00:00   0.0           2670
4  2024-03-07 10:00:00   0.0           2856

Predicting values for: FTF_Westmoreland St East Fleet St Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
         date and time  Real  LSTM_nocoords
0  2024-03-07 06:00:00   0.0           1535
1  2024-03-07 07:00:00   0.0           1561
2  2024-03-07 08:00:00   0.0           1620
3  2024-03-07 09:00:00   0.0           1704
4  2024-03-07 10:00:00   0.0           1816

Predicting values for: FTF_Westmoreland St West Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
         date and time   Real  LSTM_nocoords
0  2024-03-07 06:00:00  325.0            173
1  2024-03-07 07:00:00  594.0            259
2  2024-03-07 08:00:00  934.0            394
3  2024-03-07 09:00:00  833.0            504
4  2024-03-07 10:00:00  930.0            614

In [ ]:
allpreds.head(20)

          date and time  Real  LSTM_nocoords                        Target
0   2024-03-07 06:00:00  20.0             25  CYC_Clontarf James Larkin Rd
1   2024-03-07 07:00:00  49.0             43  CYC_Clontarf James Larkin Rd
2   2024-03-07 08:00:00  70.0             52  CYC_Clontarf James Larkin Rd
3   2024-03-07 09:00:00  51.0             51  CYC_Clontarf James Larkin Rd
4   2024-03-07 10:00:00  31.0             43  CYC_Clontarf James Larkin Rd
5   2024-03-07 11:00:00  32.0             36  CYC_Clontarf James Larkin Rd
6   2024-03-07 12:00:00  36.0             32  CYC_Clontarf James Larkin Rd
7   2024-03-07 13:00:00  33.0             32  CYC_Clontarf James Larkin Rd
8   2024-03-07 14:00:00  23.0             34  CYC_Clontarf James Larkin Rd
9   2024-03-07 15:00:00  25.0             39  CYC_Clontarf James Larkin Rd
10  2024-03-07 16:00:00  39.0             45  CYC_Clontarf James Larkin Rd
11  2024-03-07 17:00:00  68.0             50  CYC_Clontarf James Larkin Rd
12  2024-03-07 18:00:00  62.0             48  CYC_Clontarf James Larkin Rd
13  2024-03-07 19:00:00  33.0             36  CYC_Clontarf James Larkin Rd
14  2024-03-07 20:00:00   8.0             18  CYC_Clontarf James Larkin Rd
15  2024-03-07 21:00:00   7.0              9  CYC_Clontarf James Larkin Rd
16  2024-03-07 22:00:00   6.0              4  CYC_Clontarf James Larkin Rd
17  2024-03-07 23:00:00   1.0              3  CYC_Clontarf James Larkin Rd
18  2024-03-08 00:00:00   4.0              2  CYC_Clontarf James Larkin Rd
19  2024-03-08 01:00:00   2.0              2  CYC_Clontarf James Larkin Rd

## **4. RESULTS TO AZURE BLOB STORAGE**

In [ ]:
def save_blob(data, filename):
    try:
        blob_name = f"{CONTAINER_NAME}/{filename}"
        csv_data = data.to_csv(index=False)
        with fs.open(blob_name, "w") as f:
            f.write(csv_data)
        print(f"Saved to {blob_name}")
    except Exception as e:
        print(f"Error saving data to blob storage: {str(e)}")
        return False

In [ ]:
# Results
CONTAINER_NAME = "results"

save_blob(results, "rlstm_nocoords.csv")

Saved to results/rlstm_nocoords.csv

In [ ]:
# Predictions
CONTAINER_NAME = "predictions"

save_blob(allpreds, "pred_lstm_nocoords.csv")

Saved to predictions/pred_lstm_nocoords.csv