# **DEEP LEARNING MODELLING: LSTM MODEL USING GEOGRAPHICAL COORDINATES**

## **1. LIBRARIES**

### **1.1 DEPENDENCIES**

In [ ]:
! pip install adlfs azure-storage-blob
! pip install tensorflow
! pip install tqdm

Requirement already satisfied: adlfs in /usr/local/lib/python3.11/dist-packages (2024.12.0)
Requirement already satisfied: azure-storage-blob in /usr/local/lib/python3.11/dist-packages (12.26.0)
Requirement already satisfied: azure-core<2.0.0,>=1.28.0 in /usr/local/lib/python3.11/dist-packages (from adlfs) (1.35.0)
Requirement already satisfied: azure-datalake-store<0.1,>=0.0.53 in /usr/local/lib/python3.11/dist-packages (from adlfs) (0.0.53)
Requirement already satisfied: azure-identity in /usr/local/lib/python3.11/dist-packages (from adlfs) (1.24.0)
Requirement already satisfied: fsspec>=2023.12.0 in /usr/local/lib/python3.11/dist-packages (from adlfs) (2025.3.0)
Requirement already satisfied: aiohttp>=3.7.0 in /usr/local/lib/python3.11/dist-packages (from adlfs) (3.12.15)
Requirement already satisfied: cryptography>=2.1.4 in /usr/local/lib/python3.11/dist-packages (from azure-storage-blob) (43.0.3)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from azure-storage-blob) (4.14.1)
Requirement already satisfied: isodate>=0.6.1 in /usr/local/lib/python3.11/dist-packages (from azure-storage-blob) (0.7.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (6.6.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (1.20.1)
Requirement already satisfied: requests>=2.21.0 in /usr/local/lib/python3.11/dist-packages (from azure-core<2.0.0,>=1.28.0->adlfs) (2.32.3)
Requirement already satisfied: six>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from azure-core<2.0.0,>=1.28.0->adlfs) (1.17.0)
Requirement already satisfied: cffi in /usr/local/lib/python3.11/dist-packages (from azure-datalake-store<0.1,>=0.0.53->adlfs) (1.17.1)
Requirement already satisfied: msal<2,>=1.16.0 in /usr/local/lib/python3.11/dist-packages (from azure-datalake-store<0.1,>=0.0.53->adlfs) (1.33.0)
Requirement already satisfied: msal-extensions>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from azure-identity->adlfs) (1.3.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi->azure-datalake-store<0.1,>=0.0.53->adlfs) (2.22)
Requirement already satisfied: PyJWT<3,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from PyJWT[crypto]<3,>=1.0.0->msal<2,>=1.16.0->azure-datalake-store<0.1,>=0.0.53->adlfs) (2.10.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.21.0->azure-core<2.0.0,>=1.28.0->adlfs) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.21.0->azure-core<2.0.0,>=1.28.0->adlfs) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.21.0->azure-core<2.0.0,>=1.28.0->adlfs) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.21.0->azure-core<2.0.0,>=1.28.0->adlfs) (2025.8.3)
Requirement already satisfied: tensorflow in /usr/local/lib/python3.11/dist-packages (2.19.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (25.2.10)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from tensorflow) (25.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (5.29.5)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (2.32.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.1.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (4.14.1)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.17.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.74.0)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.10.0)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.5.3)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.37.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in /usr/local/lib/python3.11/dist-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.11/dist-packages (from keras>=3.5.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.11/dist-packages (from keras>=3.5.0->tensorflow) (0.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (2025.8.3)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.11/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.8.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from tensorboard~=2.19.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.1.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.11/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow) (3.0.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.5.0->tensorflow) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.5.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (4.67.1)

### **1.2 LIBRARIES**

In [ ]:
# STANDARD LIBRARY
import os
import io
import random

# DATA MANIPULATION AND ANALYSIS
import pandas as pd
import numpy as np

# DATA VISUALISATION
import matplotlib.pyplot as plt
import seaborn as sns

# AZURE CLOUD STORAGE
from adlfs import AzureBlobFileSystem
from azure.storage.blob import BlobServiceClient

# REGULAR EXPRESSIONS
import re

# TIME SERIES
from sklearn.model_selection import TimeSeriesSplit

# STANDARIZATION
from sklearn.preprocessing import StandardScaler

# EVALUATION METRICS
from sklearn.metrics import r2_score

# PROGRESS BAR
from tqdm import tqdm

# TENSORFLOW
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, LSTM, Dense, Dropout
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras import regularizers
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import mixed_precision
mixed_precision.set_global_policy("mixed_float16")

# SEEDS
np.random.seed(42)
tf.random.set_seed(42)
random.seed(42)

In [ ]:
print(tf.__version__)

2.19.0

In [ ]:
# Correctly set pandas display option for max columns and rows
pd.options.display.max_columns = None
pd.options.display.max_rows = None

## **2. LOADING DATASETS FROM AZURE BLOB STORAGE**

In [ ]:
def load_csv_from_blob(blob_name):
    blob_client = container_client.get_blob_client(blob_name)
    stream = blob_client.download_blob()
    data_bytes = stream.readall()
    data_str = data_bytes.decode("utf-8")
    return pd.read_csv(io.StringIO(data_str))

# Connection configuration
AZURE_STORAGE_ACCOUNT = "researchprojectx24104515"
AZURE_STORAGE_KEY = "bxpexO6i+Hz6n1WiipTn+sTCuLPGMS1BogMERrIrHd16DpQ0GLfQ0R33yrSw4MxsDomq5yNMgw1o+AStlx/MjA=="
connection_string = f"DefaultEndpointsProtocol=https;AccountName={AZURE_STORAGE_ACCOUNT};AccountKey={AZURE_STORAGE_KEY};EndpointSuffix=core.windows.net"
blob_service_client = BlobServiceClient.from_connection_string(connection_string)

fs = AzureBlobFileSystem(
    account_name=AZURE_STORAGE_ACCOUNT,
    account_key=AZURE_STORAGE_KEY
)

In [ ]:
# Establish connection to preprocessed dataset
CONTAINER_NAME = "preprocessed"
container_client = blob_service_client.get_container_client(CONTAINER_NAME)

file_name = "preprocessed.csv"
data = load_csv_from_blob(file_name)
print(f"Loaded '{file_name}' with shape: {data.shape}")

Loaded 'preprocessed.csv' with shape: (53424, 44)

In [ ]:
print("Preprocessed Data:")
print(data.shape)
data.head()

Preprocessed Data:
(53424, 44)

,date and time,CYC_Clontarf James Larkin Rd,CYC_Clontarf Pebble Beach Carpark,CYC_Grove Road Totem,CYC_North Strand Rd N B,CYC_Richmond Street Cyclists 1 Merged,CYC_Richmond Street Cyclists 2 Merged,FTF_Aston Quay Merged,FTF_Capel St Mary St Merged,FTF_College St Dame St Merged,FTF_Dame St Merged,FTF_Dolier St Burgh Quay Merged,FTF_Grafton St Monsoon Merged,FTF_Grafton St Nassau St Suffolk St,FTF_Henry St Merged,FTF_Mary St Merged,FTF_Oconnell St Princes St North Merged,FTF_Talbot St Guineys Merged,FTF_Westmoreland St East Fleet St Merged,FTF_Westmoreland St West Merged,WTH_rain,WTH_temp,WTH_wetb,WTH_dewpt,WTH_vappr,WTH_rhum,WTH_msl,TEMP_year,TEMP_holiday,WTH_temp_3h,WTH_rain_int,WTH_dew_spread,WTH_prob_cond,WTH_severe,TEMP_hour_sin,TEMP_hour_cos,TEMP_day_sin,TEMP_day_cos,TEMP_month_sin,TEMP_month_cos,TEMP_weekend,TEMP_mor_peak,TEMP_eve_peak,TEMP_bus_hours
0,2019-01-01 00:00:00,0.0,0.0,12.0,16.0,0.0,0.0,0.0,238.0,0.0,0.0,0.0,140.0,0.0,597.0,163.0,1914.0,0.0,1670.0,1988.0,0.0,9.6,7.8,5.6,9.1,76.0,1035.1,2019,0,0.000000,0,4.0,0,0,0.000000,1.000000,0.781831,0.62349,0.5,0.866025,0,0,0,0
1,2019-01-01 01:00:00,0.0,0.0,17.0,14.0,0.0,0.0,0.0,173.0,0.0,0.0,0.0,215.0,0.0,359.0,102.0,885.0,0.0,767.0,1270.0,0.0,8.6,7.1,5.3,8.9,79.0,1035.1,2019,0,0.000000,0,3.3,0,0,0.258819,0.965926,0.781831,0.62349,0.5,0.866025,0,0,0,0
2,2019-01-01 02:00:00,0.0,0.0,18.0,9.0,0.0,0.0,0.0,121.0,0.0,0.0,0.0,210.0,0.0,317.0,63.0,984.0,0.0,642.0,1589.0,0.0,8.3,6.9,5.3,8.9,81.0,1034.9,2019,0,8.833333,0,3.0,0,0,0.500000,0.866025,0.781831,0.62349,0.5,0.866025,0,0,0,0
3,2019-01-01 03:00:00,0.0,0.0,18.0,15.0,0.0,0.0,0.0,174.0,0.0,0.0,0.0,204.0,0.0,313.0,59.0,935.0,0.0,582.0,1534.0,0.0,9.1,7.6,5.8,9.2,79.0,1035.5,2019,0,8.666667,0,3.3,0,0,0.707107,0.707107,0.781831,0.62349,0.5,0.866025,0,0,0,0
4,2019-01-01 04:00:00,0.0,0.0,12.0,8.0,0.0,0.0,0.0,82.0,0.0,0.0,0.0,88.0,0.0,172.0,46.0,390.0,0.0,143.0,610.0,0.0,9.2,7.7,5.9,9.3,79.0,1035.7,2019,0,8.866667,0,3.3,0,0,0.866025,0.500000,0.781831,0.62349,0.5,0.866025,0,0,0,0

In [ ]:
# Establish connection to counters dataset
CONTAINER_NAME = "preprocessed"
container_client = blob_service_client.get_container_client(CONTAINER_NAME)

file_name = "counters.csv"
counters = load_csv_from_blob(file_name)
print(f"Loaded '{file_name}' with shape: {counters.shape}")

Loaded 'counters.csv' with shape: (31, 3)

In [ ]:
print("Counter Locations Data:")
print(counters.shape)
counters

Counter Locations Data:
(31, 3)

                                               Target   Latitude  Longitude
0                        CYC_Clontarf James Larkin Rd  53.368540  -6.170320
1                   CYC_Clontarf Pebble Beach Carpark  53.358250  -6.191070
2                                CYC_Grove Road Totem  53.329644  -6.270178
3                             CYC_North Strand Rd N B  53.358520  -6.241270
4               CYC_Richmond Street Cyclists 1 Merged  53.332160  -6.264400
5               CYC_Richmond Street Cyclists 2 Merged  53.332160  -6.264400
6                               FTF_Aston Quay Merged  53.346680  -6.259880
7                           FTF_Bachelors Walk Merged  53.347440  -6.260100
8                          FTF_Baggot St Lower Merged  53.334540  -6.245620
9                  FTF_Baggot St Upper Mespil Rd Bank  53.333770  -6.244510
10                        FTF_Capel St Mary St Merged  53.348530  -6.268800
11                      FTF_College St Dame St Merged  53.345060  -6.258880
12                    FTF_Dolier St Burgh Quay Merged  53.346840  -6.258870
13                                 FTF_Dame St Merged  53.344470  -6.261520
14                               FTF_Dawson St Merged  53.341194  -6.258337
15                      FTF_Grafton St Monsoon Merged  53.340770  -6.260580
16                FTF_Grafton St Nassau St Suffolk St  53.343550  -6.259320
17  FTF_Grand Canal St Upper Clanwilliam Place Goo...  53.338550  -6.238980
18                                FTF_Henry St Merged  53.348760  -6.262860
19                                 FTF_Mary St Merged  53.348650  -6.266850
20     FTF_North Wall Quay Samuel Beckett Bridge East  53.347460  -6.240990
21     FTF_North Wall Quay Samuel Beckett Bridge West  53.347500  -6.241400
22                      FTF_Oconnell St Pennys Merged  53.348790  -6.259690
23            FTF_Oconnell St Princes St North Merged  53.348950  -6.260040
24                FTF_Phibsborough Rd Enniskerry Road  53.363540  -6.272080
25   FTF_Richmond St South Portabello Harbour Inbound  53.330420  -6.264480
26  FTF_Richmond St South Portabello Harbour Outbound  53.330330  -6.264250
27                       FTF_Talbot St Guineys Merged  53.350820  -6.255400
28              FTF_Talbot St Murrays Pharmacy Merged  53.350535  -6.253992
29           FTF_Westmoreland St East Fleet St Merged  53.345310  -6.259330
30                    FTF_Westmoreland St West Merged  53.346480  -6.259180

### **2.1 DEFINE FEATURE CATEGORIES**

In [ ]:
data.head()

,date and time,CYC_Clontarf James Larkin Rd,CYC_Clontarf Pebble Beach Carpark,CYC_Grove Road Totem,CYC_North Strand Rd N B,CYC_Richmond Street Cyclists 1 Merged,CYC_Richmond Street Cyclists 2 Merged,FTF_Aston Quay Merged,FTF_Capel St Mary St Merged,FTF_College St Dame St Merged,FTF_Dame St Merged,FTF_Dolier St Burgh Quay Merged,FTF_Grafton St Monsoon Merged,FTF_Grafton St Nassau St Suffolk St,FTF_Henry St Merged,FTF_Mary St Merged,FTF_Oconnell St Princes St North Merged,FTF_Talbot St Guineys Merged,FTF_Westmoreland St East Fleet St Merged,FTF_Westmoreland St West Merged,WTH_rain,WTH_temp,WTH_wetb,WTH_dewpt,WTH_vappr,WTH_rhum,WTH_msl,TEMP_year,TEMP_holiday,WTH_temp_3h,WTH_rain_int,WTH_dew_spread,WTH_prob_cond,WTH_severe,TEMP_hour_sin,TEMP_hour_cos,TEMP_day_sin,TEMP_day_cos,TEMP_month_sin,TEMP_month_cos,TEMP_weekend,TEMP_mor_peak,TEMP_eve_peak,TEMP_bus_hours
0,2019-01-01 00:00:00,0.0,0.0,12.0,16.0,0.0,0.0,0.0,238.0,0.0,0.0,0.0,140.0,0.0,597.0,163.0,1914.0,0.0,1670.0,1988.0,0.0,9.6,7.8,5.6,9.1,76.0,1035.1,2019,0,0.000000,0,4.0,0,0,0.000000,1.000000,0.781831,0.62349,0.5,0.866025,0,0,0,0
1,2019-01-01 01:00:00,0.0,0.0,17.0,14.0,0.0,0.0,0.0,173.0,0.0,0.0,0.0,215.0,0.0,359.0,102.0,885.0,0.0,767.0,1270.0,0.0,8.6,7.1,5.3,8.9,79.0,1035.1,2019,0,0.000000,0,3.3,0,0,0.258819,0.965926,0.781831,0.62349,0.5,0.866025,0,0,0,0
2,2019-01-01 02:00:00,0.0,0.0,18.0,9.0,0.0,0.0,0.0,121.0,0.0,0.0,0.0,210.0,0.0,317.0,63.0,984.0,0.0,642.0,1589.0,0.0,8.3,6.9,5.3,8.9,81.0,1034.9,2019,0,8.833333,0,3.0,0,0,0.500000,0.866025,0.781831,0.62349,0.5,0.866025,0,0,0,0
3,2019-01-01 03:00:00,0.0,0.0,18.0,15.0,0.0,0.0,0.0,174.0,0.0,0.0,0.0,204.0,0.0,313.0,59.0,935.0,0.0,582.0,1534.0,0.0,9.1,7.6,5.8,9.2,79.0,1035.5,2019,0,8.666667,0,3.3,0,0,0.707107,0.707107,0.781831,0.62349,0.5,0.866025,0,0,0,0
4,2019-01-01 04:00:00,0.0,0.0,12.0,8.0,0.0,0.0,0.0,82.0,0.0,0.0,0.0,88.0,0.0,172.0,46.0,390.0,0.0,143.0,610.0,0.0,9.2,7.7,5.9,9.3,79.0,1035.7,2019,0,8.866667,0,3.3,0,0,0.866025,0.500000,0.781831,0.62349,0.5,0.866025,0,0,0,0

In [ ]:
# Interaction features created with weather features
interactionf = ["WTH_dew_spread", "WTH_prob_cond", "WTH_severe"]

# Using regex to get all temporal and weather prefix patterns
temp_pattern = re.compile(r"^TEMP_")
wth_pattern = re.compile(r"^WTH_")

# Using regex to get all temporal and weather features
temporalf = [col for col in data.columns if temp_pattern.match(col)]
weatherf = [col for col in data.columns if wth_pattern.match(col) and col not in interactionf]

In [ ]:
weatherf

['WTH_rain',
 'WTH_temp',
 'WTH_wetb',
 'WTH_dewpt',
 'WTH_vappr',
 'WTH_rhum',
 'WTH_msl',
 'WTH_temp_3h',
 'WTH_rain_int']

In [ ]:
temporalf

['TEMP_year',
 'TEMP_holiday',
 'TEMP_hour_sin',
 'TEMP_hour_cos',
 'TEMP_day_sin',
 'TEMP_day_cos',
 'TEMP_month_sin',
 'TEMP_month_cos',
 'TEMP_weekend',
 'TEMP_mor_peak',
 'TEMP_eve_peak',
 'TEMP_bus_hours']

In [ ]:
# Combine all features
fcolumns = weatherf + temporalf + interactionf

# Extract cycle and footfall targets
cycle_t = [col for col in data.columns if col.startswith("CYC_")]
footfall_t = [col for col in data.columns if col.startswith("FTF_")]
targets = cycle_t + footfall_t

# Prepare feature matrix
X = data[fcolumns].copy()
y = data[targets].copy()

# Handle missing values
X = X.ffill().bfill()
y = y.fillna(0)

print(f"Features shape: {X.shape}")
print(f"Targets shape: {y.shape}")
print(f"Feature columns: {len(fcolumns)}")

Features shape: (53424, 24)
Targets shape: (53424, 19)
Feature columns: 24

In [ ]:
targets

['CYC_Clontarf James Larkin Rd',
 'CYC_Clontarf Pebble Beach Carpark',
 'CYC_Grove Road Totem',
 'CYC_North Strand Rd N B',
 'CYC_Richmond Street Cyclists 1 Merged',
 'CYC_Richmond Street Cyclists 2 Merged',
 'FTF_Aston Quay Merged',
 'FTF_Capel St Mary St Merged',
 'FTF_College St Dame St Merged',
 'FTF_Dame St Merged',
 'FTF_Dolier St Burgh Quay Merged',
 'FTF_Grafton St Monsoon Merged',
 'FTF_Grafton St Nassau St Suffolk St',
 'FTF_Henry St Merged',
 'FTF_Mary St Merged',
 'FTF_Oconnell St Princes St North Merged',
 'FTF_Talbot St Guineys Merged',
 'FTF_Westmoreland St East Fleet St Merged',
 'FTF_Westmoreland St West Merged']

# **3. DEEP LEARNING MODELLING : LSTM**

### **3.1 DEFINE LSTM MODEL**

In [ ]:
# Crating LSTM sequences for multiple targets

def lstm_sequences(data, targets, features, counters, seq_len=24):
    # Scale features for all targets
    f_scaler = MinMaxScaler()
    f_data = f_scaler.fit_transform(data[features])

    # Dictionaries to store sequences and scalers
    X_data = {}
    y_data = {}
    t_scalers = {}

    # Ensure Target column in counters has no leading/trailing spaces
    counters["Target"] = counters["Target"].astype(str).str.strip()

    for t in targets:
        # Search for matching target in counters DataFrame
        match = counters.loc[counters["Target"] == t]

        # If no match is found, skip this target
        if match.empty:
            print(f"Warning: Target '{t}' not found in counters DataFrame. Skipping...")
            continue

        # Get latitude and longitude for the target
        lat = match["Latitude"].values[0]
        lon = match["Longitude"].values[0]

        # Scale target values
        y = data[t].values.reshape(-1, 1)
        t_scaler = MinMaxScaler()
        y_scaled = t_scaler.fit_transform(y)

        # Create LSTM sequences
        X, y_seq = [], []
        for i in range(seq_len, len(f_data)):
            # Original feature sequence
            seq = f_data[i-seq_len:i]
            # Add same coordinates across the sequence
            coords = np.tile([lat, lon], (seq_len, 1))
            # Combine features and coordinates
            seq_with_coords = np.concatenate([seq, coords], axis=1)
            X.append(seq_with_coords)
            y_seq.append(y_scaled[i])

        # Save results
        X_data[t] = np.array(X, dtype=np.float32)
        y_data[t] = np.array(y_seq, dtype=np.float32)
        t_scalers[t] = t_scaler

    return X_data, y_data, f_scaler, t_scalers



# Time series split

def ts_split(X, y, train_ratio=0.7, val_ratio=0.15):
    # Index for training and validation
    n_samples = len(X)
    train_end = int(n_samples * train_ratio)
    val_end = int(n_samples * (train_ratio + val_ratio))

    # Define train, test and validation sets
    X_train = X[:train_end]
    y_train = y[:train_end]

    X_val = X[train_end:val_end]
    y_val = y[train_end:val_end]

    X_test = X[val_end:]
    y_test = y[val_end:]

    return X_train, X_val, X_test, y_train, y_val, y_test

# LSTM model

def lstm_model(input_shape):
    reg_strength = 1e-4  # regularisation L2 level

    model = Sequential()
    model.add(Input(shape=input_shape))

    # First LSTM layer
    model.add(LSTM(64, return_sequences=True,
                   kernel_regularizer=regularizers.l2(reg_strength)))
    model.add(Dropout(0.3))

    # Second LSTM layer
    model.add(LSTM(32, return_sequences=False,
                   kernel_regularizer=regularizers.l2(reg_strength)))
    model.add(Dropout(0.3))

    # Middle dense layer
    model.add(Dense(64, activation="relu",
                    kernel_regularizer=regularizers.l2(reg_strength)))
    model.add(Dropout(0.2))

    # Output with one neuron for regression
    model.add(Dense(1))

    # Model compilation
    model.compile(optimizer=Adam(learning_rate=0.001),
                  loss="mse",
                  metrics=["mae"])

    return model

# Callback: Early stopping if improvement is not seen after 5 epochs
early_stop = EarlyStopping(monitor="val_loss", patience=5, restore_best_weights=True)

### **3.2 TRAIN MODEL**

In [ ]:
def train_lstm(target_name, X, y, strategy, callbacks=None):
    print(f"\nTraining model for: {target_name}")

    # Splittng data into training, validation, and test sets
    X_train, X_val, X_test, y_train, y_val, y_test = ts_split(X, y)

    # Distribution startegy employed
    print(f"Using strategy: {strategy.__class__.__name__}")

    # Build the LSTM model
    with strategy.scope():
        model = lstm_model(input_shape=X_train.shape[1:])

        # If there are no callbacks defined, this will be as default for early stopping and learning rate
        if callbacks is None:
            early_stopping = EarlyStopping(
                monitor="val_loss",
                # Stop if improvement is not seen after 10 epochs
                patience=10,
                restore_best_weights=True
                )
            reduce_lr = ReduceLROnPlateau(
                monitor="val_loss",
                # Reduce learning rate to half of the value
                factor=0.5,
                # Stop if improvement is not seen after 5 epochs
                patience=5,
                # Do not reduce learning rate below this value
                min_lr=1e-6
                )
            callbacks = [early_stopping, reduce_lr]

        # Training the model
        history = model.fit(
            X_train, y_train,
            # Max epochs allowed
            epochs=100,
            # Samples number per training batch
            batch_size=1024,
            # Validation data for monitoring
            validation_data=(X_val, y_val),
            # Defined callbacks to use
            callbacks=callbacks,
            verbose=1
        )

    print(f"------Training completed for: {target_name}")
    return model, history, X_test, y_test

### **3.3 MODEL VALUATION METRICS**

In [ ]:
def evaluate_mtarget(model, X_test, y_test, target_scaler, target_name, target_idx, n_targets):
    print(f"\n----------- Evaluating model for: {target_name} ({target_idx + 1}/{n_targets})")

    # Predictions
    y_pred = model.predict(X_test)

    # Verifying if y_test is in normalised scale
    if np.max(y_test) <= 1.0:
        y_true = target_scaler.inverse_transform(y_test.reshape(-1, 1))
    else:
        print("Warning: y_test seems to be scaled. Evaluation metrics could be inconsistent.")
        y_true = y_test.reshape(-1, 1)

    # Descale predictions
    y_pred = target_scaler.inverse_transform(y_pred)
    y_pred = np.round(y_pred).astype(int)

    # Evaluation metrics
    rmse = np.sqrt(np.mean((y_true - y_pred) ** 2))
    mae = np.mean(np.abs(y_true - y_pred))

    # Avoid division by zero in MAPE
    mask = y_true != 0
    if np.any(mask):
        mape = np.mean(np.abs((y_true[mask] - y_pred[mask]) / y_true[mask])) * 100
    else:
        mape = np.nan  # Unable to calculate MAPE

    r2 = r2_score(y_true, y_pred)

    # Results
    print("Evaluation Metrics:")
    print(f" -RMSE : {rmse:.2f}")
    print(f" -MAE  : {mae:.2f}")
    print(f" -MAPE : {mape:.2f}%")
    print(f" -R²   : {r2:.4f}")

    return {
        "RMSE": rmse,
        "MAE": mae,
        "MAPE": mape,
        "R2": r2
    }

### **3.4 APPLYING LSTM**

In [ ]:
# Hours during the day
sequence_length = 24

X_lstm_dict, y_lstm_dict, feature_scaler_lstm, target_scaler_dict = lstm_sequences(
    pd.concat([X, y], axis=1),
    targets,
    fcolumns,
    counters,
    sequence_length
)

strategy = tf.distribute.get_strategy()
print("Shape of a sequence with coordinates:", X_lstm_dict[targets[0]].shape)

Shape of a sequence with coordinates: (53400, 24, 26)

In [ ]:
models = {}
histories = {}
results = {}
test_sets = {}

n_targets = len(targets)

for idx, target_name in enumerate(targets, 1):
    print(f"\n--- Processing target {idx} out of {n_targets}: {target_name}")

    # Get specific data for target
    X_data = X_lstm_dict[target_name]
    y_data = y_lstm_dict[target_name]

    # Training model for target
    model, history, X_test, y_test = train_lstm(
        target_name,
        X_data,
        y_data,
        strategy,
        callbacks=[early_stop]
    )

    # Save model and historical
    models[target_name] = model
    histories[target_name] = history

    # Save test sets for further evaluation
    test_sets[target_name] = (X_test, y_test)

    # Target scaler for predictions and real values descalation
    target_scaler = target_scaler_dict[target_name]

    # Evaluate the model
    metrics = evaluate_mtarget(
        model,
        X_test,
        y_test,
        target_scaler,
        target_name,
        idx,
        n_targets
    )

    results[target_name] = metrics

print("\nTraining and evaluation completed for all targets.")

--- Processing target 1 out of 19: CYC_Clontarf James Larkin Rd

Training model for: CYC_Clontarf James Larkin Rd
Using strategy: _DefaultDistributionStrategy
Epoch 1/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - loss: 0.0382 - mae: 0.1105 - val_loss: 0.0231 - val_mae: 0.0659
Epoch 2/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0200 - mae: 0.0600 - val_loss: 0.0205 - val_mae: 0.0670
Epoch 3/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0167 - mae: 0.0576 - val_loss: 0.0151 - val_mae: 0.0608
Epoch 4/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0138 - mae: 0.0506 - val_loss: 0.0121 - val_mae: 0.0560
Epoch 5/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0117 - mae: 0.0442 - val_loss: 0.0136 - val_mae: 0.0738
Epoch 6/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0100 - mae: 0.0383 - val_loss: 0.0108 - val_mae: 0.0590
Epoch 7/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0089 - mae: 0.0351 - val_loss: 0.0100 - val_mae: 0.0529
Epoch 8/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0082 - mae: 0.0336 - val_loss: 0.0118 - val_mae: 0.0672
Epoch 9/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0078 - mae: 0.0334 - val_loss: 0.0079 - val_mae: 0.0440
Epoch 10/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0071 - mae: 0.0307 - val_loss: 0.0082 - val_mae: 0.0471
Epoch 11/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0066 - mae: 0.0297 - val_loss: 0.0078 - val_mae: 0.0474
Epoch 12/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0062 - mae: 0.0291 - val_loss: 0.0065 - val_mae: 0.0418
Epoch 13/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0060 - mae: 0.0287 - val_loss: 0.0060 - val_mae: 0.0402
Epoch 14/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0273 - val_loss: 0.0071 - val_mae: 0.0456
Epoch 15/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0273 - val_loss: 0.0060 - val_mae: 0.0439
Epoch 16/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0050 - mae: 0.0254 - val_loss: 0.0053 - val_mae: 0.0387
Epoch 17/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0046 - mae: 0.0244 - val_loss: 0.0048 - val_mae: 0.0346
Epoch 18/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0045 - mae: 0.0242 - val_loss: 0.0044 - val_mae: 0.0322
Epoch 19/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0041 - mae: 0.0225 - val_loss: 0.0041 - val_mae: 0.0297
Epoch 20/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0046 - mae: 0.0252 - val_loss: 0.0043 - val_mae: 0.0347
Epoch 21/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0037 - mae: 0.0210 - val_loss: 0.0037 - val_mae: 0.0286
Epoch 22/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0038 - mae: 0.0221 - val_loss: 0.0043 - val_mae: 0.0365
Epoch 23/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0035 - mae: 0.0212 - val_loss: 0.0041 - val_mae: 0.0366
Epoch 24/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0034 - mae: 0.0205 - val_loss: 0.0043 - val_mae: 0.0387
Epoch 25/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0036 - mae: 0.0221 - val_loss: 0.0038 - val_mae: 0.0351
Epoch 26/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0030 - mae: 0.0198 - val_loss: 0.0040 - val_mae: 0.0380
------Training completed for: CYC_Clontarf James Larkin Rd

----------- Evaluating model for: CYC_Clontarf James Larkin Rd (2/19)
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step
Evaluation Metrics:
 -RMSE : 28.04
 -MAE  : 21.95
 -MAPE : 380.82%
 -R²   : 0.4685

--- Processing target 2 out of 19: CYC_Clontarf Pebble Beach Carpark

Training model for: CYC_Clontarf Pebble Beach Carpark
Using strategy: _DefaultDistributionStrategy
Epoch 1/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0878 - mae: 0.2013 - val_loss: 0.0236 - val_mae: 0.0678
Epoch 2/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0237 - mae: 0.0730 - val_loss: 0.0258 - val_mae: 0.0777
Epoch 3/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0197 - mae: 0.0627 - val_loss: 0.0231 - val_mae: 0.0736
Epoch 4/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0176 - mae: 0.0583 - val_loss: 0.0206 - val_mae: 0.0673
Epoch 5/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0160 - mae: 0.0541 - val_loss: 0.0145 - val_mae: 0.0512
Epoch 6/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0137 - mae: 0.0462 - val_loss: 0.0138 - val_mae: 0.0600
Epoch 7/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0124 - mae: 0.0410 - val_loss: 0.0170 - val_mae: 0.0821
Epoch 8/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0118 - mae: 0.0391 - val_loss: 0.0136 - val_mae: 0.0624
Epoch 9/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0111 - mae: 0.0372 - val_loss: 0.0143 - val_mae: 0.0693
Epoch 10/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0106 - mae: 0.0358 - val_loss: 0.0177 - val_mae: 0.0888
Epoch 11/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0102 - mae: 0.0353 - val_loss: 0.0129 - val_mae: 0.0642
Epoch 12/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0098 - mae: 0.0341 - val_loss: 0.0155 - val_mae: 0.0800
Epoch 13/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0096 - mae: 0.0341 - val_loss: 0.0142 - val_mae: 0.0707
Epoch 14/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0091 - mae: 0.0328 - val_loss: 0.0111 - val_mae: 0.0547
Epoch 15/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0088 - mae: 0.0319 - val_loss: 0.0097 - val_mae: 0.0447
Epoch 16/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0083 - mae: 0.0301 - val_loss: 0.0086 - val_mae: 0.0387
Epoch 17/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0081 - mae: 0.0300 - val_loss: 0.0081 - val_mae: 0.0372
Epoch 18/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0077 - mae: 0.0292 - val_loss: 0.0077 - val_mae: 0.0355
Epoch 19/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0074 - mae: 0.0275 - val_loss: 0.0085 - val_mae: 0.0459
Epoch 20/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0069 - mae: 0.0264 - val_loss: 0.0116 - val_mae: 0.0661
Epoch 21/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0068 - mae: 0.0263 - val_loss: 0.0084 - val_mae: 0.0485
Epoch 22/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0065 - mae: 0.0249 - val_loss: 0.0091 - val_mae: 0.0528
Epoch 23/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0063 - mae: 0.0244 - val_loss: 0.0071 - val_mae: 0.0382
Epoch 24/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0062 - mae: 0.0239 - val_loss: 0.0086 - val_mae: 0.0512
Epoch 25/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0058 - mae: 0.0229 - val_loss: 0.0103 - val_mae: 0.0632
Epoch 26/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0059 - mae: 0.0234 - val_loss: 0.0076 - val_mae: 0.0465
Epoch 27/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0221 - val_loss: 0.0112 - val_mae: 0.0701
Epoch 28/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0058 - mae: 0.0241 - val_loss: 0.0123 - val_mae: 0.0749
------Training completed for: CYC_Clontarf Pebble Beach Carpark

----------- Evaluating model for: CYC_Clontarf Pebble Beach Carpark (3/19)
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step
Evaluation Metrics:
 -RMSE : 75.00
 -MAE  : 63.05
 -MAPE : 657.11%
 -R²   : -0.8717

--- Processing target 3 out of 19: CYC_Grove Road Totem

Training model for: CYC_Grove Road Totem
Using strategy: _DefaultDistributionStrategy
Epoch 1/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0691 - mae: 0.1705 - val_loss: 0.0258 - val_mae: 0.0694
Epoch 2/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0270 - mae: 0.0815 - val_loss: 0.0229 - val_mae: 0.0680
Epoch 3/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0231 - mae: 0.0745 - val_loss: 0.0213 - val_mae: 0.0671
Epoch 4/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0210 - mae: 0.0721 - val_loss: 0.0186 - val_mae: 0.0648
Epoch 5/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0194 - mae: 0.0694 - val_loss: 0.0178 - val_mae: 0.0588
Epoch 6/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0181 - mae: 0.0657 - val_loss: 0.0166 - val_mae: 0.0566
Epoch 7/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0166 - mae: 0.0610 - val_loss: 0.0152 - val_mae: 0.0510
Epoch 8/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0153 - mae: 0.0563 - val_loss: 0.0144 - val_mae: 0.0501
Epoch 9/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0143 - mae: 0.0537 - val_loss: 0.0144 - val_mae: 0.0513
Epoch 10/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0127 - mae: 0.0509 - val_loss: 0.0104 - val_mae: 0.0375
Epoch 11/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0108 - mae: 0.0444 - val_loss: 0.0098 - val_mae: 0.0379
Epoch 12/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0100 - mae: 0.0417 - val_loss: 0.0103 - val_mae: 0.0411
Epoch 13/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0095 - mae: 0.0405 - val_loss: 0.0087 - val_mae: 0.0358
Epoch 14/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0092 - mae: 0.0399 - val_loss: 0.0083 - val_mae: 0.0368
Epoch 15/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0088 - mae: 0.0390 - val_loss: 0.0085 - val_mae: 0.0371
Epoch 16/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0085 - mae: 0.0385 - val_loss: 0.0076 - val_mae: 0.0349
Epoch 17/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0080 - mae: 0.0370 - val_loss: 0.0082 - val_mae: 0.0385
Epoch 18/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0079 - mae: 0.0371 - val_loss: 0.0084 - val_mae: 0.0384
Epoch 19/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0076 - mae: 0.0367 - val_loss: 0.0079 - val_mae: 0.0387
Epoch 20/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0073 - mae: 0.0358 - val_loss: 0.0081 - val_mae: 0.0395
Epoch 21/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0071 - mae: 0.0356 - val_loss: 0.0081 - val_mae: 0.0379
------Training completed for: CYC_Grove Road Totem

----------- Evaluating model for: CYC_Grove Road Totem (4/19)
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step
Evaluation Metrics:
 -RMSE : 74.74
 -MAE  : 41.92
 -MAPE : 144.18%
 -R²   : 0.6090

--- Processing target 4 out of 19: CYC_North Strand Rd N B

Training model for: CYC_North Strand Rd N B
Using strategy: _DefaultDistributionStrategy
Epoch 1/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 3s 23ms/step - loss: 0.0439 - mae: 0.1210 - val_loss: 0.0163 - val_mae: 0.0548
Epoch 2/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0235 - mae: 0.0670 - val_loss: 0.0127 - val_mae: 0.0460
Epoch 3/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0197 - mae: 0.0601 - val_loss: 0.0108 - val_mae: 0.0370
Epoch 4/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0165 - mae: 0.0539 - val_loss: 0.0101 - val_mae: 0.0311
Epoch 5/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0135 - mae: 0.0462 - val_loss: 0.0082 - val_mae: 0.0246
Epoch 6/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0118 - mae: 0.0422 - val_loss: 0.0072 - val_mae: 0.0258
Epoch 7/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0108 - mae: 0.0402 - val_loss: 0.0067 - val_mae: 0.0261
Epoch 8/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0101 - mae: 0.0390 - val_loss: 0.0066 - val_mae: 0.0303
Epoch 9/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0092 - mae: 0.0374 - val_loss: 0.0064 - val_mae: 0.0310
Epoch 10/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0086 - mae: 0.0363 - val_loss: 0.0060 - val_mae: 0.0294
Epoch 11/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0083 - mae: 0.0367 - val_loss: 0.0057 - val_mae: 0.0288
Epoch 12/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0078 - mae: 0.0356 - val_loss: 0.0060 - val_mae: 0.0336
Epoch 13/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0074 - mae: 0.0351 - val_loss: 0.0057 - val_mae: 0.0320
Epoch 14/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0070 - mae: 0.0344 - val_loss: 0.0046 - val_mae: 0.0224
Epoch 15/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0070 - mae: 0.0350 - val_loss: 0.0047 - val_mae: 0.0257
Epoch 16/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0064 - mae: 0.0335 - val_loss: 0.0049 - val_mae: 0.0313
Epoch 17/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0064 - mae: 0.0345 - val_loss: 0.0044 - val_mae: 0.0295
Epoch 18/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0060 - mae: 0.0333 - val_loss: 0.0040 - val_mae: 0.0254
Epoch 19/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0059 - mae: 0.0334 - val_loss: 0.0039 - val_mae: 0.0241
Epoch 20/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0057 - mae: 0.0330 - val_loss: 0.0041 - val_mae: 0.0283
Epoch 21/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0054 - mae: 0.0326 - val_loss: 0.0038 - val_mae: 0.0269
Epoch 22/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0053 - mae: 0.0329 - val_loss: 0.0032 - val_mae: 0.0200
Epoch 23/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0053 - mae: 0.0332 - val_loss: 0.0036 - val_mae: 0.0287
Epoch 24/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0052 - mae: 0.0330 - val_loss: 0.0034 - val_mae: 0.0249
Epoch 25/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0049 - mae: 0.0318 - val_loss: 0.0033 - val_mae: 0.0248
Epoch 26/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0048 - mae: 0.0320 - val_loss: 0.0027 - val_mae: 0.0169
Epoch 27/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0047 - mae: 0.0323 - val_loss: 0.0032 - val_mae: 0.0286
Epoch 28/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0047 - mae: 0.0322 - val_loss: 0.0029 - val_mae: 0.0249
Epoch 29/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0045 - mae: 0.0315 - val_loss: 0.0028 - val_mae: 0.0231
Epoch 30/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0043 - mae: 0.0311 - val_loss: 0.0029 - val_mae: 0.0249
Epoch 31/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0044 - mae: 0.0317 - val_loss: 0.0024 - val_mae: 0.0195
Epoch 32/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0043 - mae: 0.0310 - val_loss: 0.0024 - val_mae: 0.0197
Epoch 33/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0041 - mae: 0.0306 - val_loss: 0.0023 - val_mae: 0.0188
Epoch 34/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0040 - mae: 0.0305 - val_loss: 0.0023 - val_mae: 0.0194
Epoch 35/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0040 - mae: 0.0304 - val_loss: 0.0027 - val_mae: 0.0261
Epoch 36/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0039 - mae: 0.0303 - val_loss: 0.0023 - val_mae: 0.0196
Epoch 37/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0037 - mae: 0.0294 - val_loss: 0.0023 - val_mae: 0.0173
Epoch 38/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0036 - mae: 0.0293 - val_loss: 0.0029 - val_mae: 0.0237
Epoch 39/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0036 - mae: 0.0294 - val_loss: 0.0023 - val_mae: 0.0169
Epoch 40/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0034 - mae: 0.0282 - val_loss: 0.0021 - val_mae: 0.0140
Epoch 41/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0033 - mae: 0.0276 - val_loss: 0.0023 - val_mae: 0.0186
Epoch 42/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0033 - mae: 0.0279 - val_loss: 0.0022 - val_mae: 0.0169
Epoch 43/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0033 - mae: 0.0279 - val_loss: 0.0026 - val_mae: 0.0195
Epoch 44/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0033 - mae: 0.0281 - val_loss: 0.0016 - val_mae: 0.0100
Epoch 45/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0031 - mae: 0.0266 - val_loss: 0.0028 - val_mae: 0.0195
Epoch 46/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0031 - mae: 0.0278 - val_loss: 0.0023 - val_mae: 0.0148
Epoch 47/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0031 - mae: 0.0271 - val_loss: 0.0018 - val_mae: 0.0128
Epoch 48/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0029 - mae: 0.0257 - val_loss: 0.0012 - val_mae: 0.0094
Epoch 49/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0028 - mae: 0.0255 - val_loss: 9.9430e-04 - val_mae: 0.0113
Epoch 50/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0029 - mae: 0.0265 - val_loss: 0.0012 - val_mae: 0.0097
Epoch 51/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0027 - mae: 0.0251 - val_loss: 0.0018 - val_mae: 0.0133
Epoch 52/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0027 - mae: 0.0252 - val_loss: 8.7184e-04 - val_mae: 0.0099
Epoch 53/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0026 - mae: 0.0252 - val_loss: 8.8787e-04 - val_mae: 0.0085
Epoch 54/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0026 - mae: 0.0251 - val_loss: 8.6570e-04 - val_mae: 0.0107
Epoch 55/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0026 - mae: 0.0251 - val_loss: 0.0014 - val_mae: 0.0111
Epoch 56/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0025 - mae: 0.0244 - val_loss: 0.0015 - val_mae: 0.0139
Epoch 57/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0025 - mae: 0.0243 - val_loss: 8.2306e-04 - val_mae: 0.0105
Epoch 58/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0023 - mae: 0.0231 - val_loss: 0.0014 - val_mae: 0.0118
Epoch 59/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0024 - mae: 0.0241 - val_loss: 0.0017 - val_mae: 0.0134
Epoch 60/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0024 - mae: 0.0243 - val_loss: 9.3545e-04 - val_mae: 0.0109
Epoch 61/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0022 - mae: 0.0231 - val_loss: 0.0014 - val_mae: 0.0133
Epoch 62/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0024 - mae: 0.0245 - val_loss: 6.9859e-04 - val_mae: 0.0104
Epoch 63/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0022 - mae: 0.0231 - val_loss: 9.3803e-04 - val_mae: 0.0085
Epoch 64/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0023 - mae: 0.0236 - val_loss: 6.3521e-04 - val_mae: 0.0096
Epoch 65/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0022 - mae: 0.0231 - val_loss: 6.5303e-04 - val_mae: 0.0103
Epoch 66/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0022 - mae: 0.0231 - val_loss: 6.0682e-04 - val_mae: 0.0097
Epoch 67/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0023 - mae: 0.0237 - val_loss: 8.9344e-04 - val_mae: 0.0111
Epoch 68/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0022 - mae: 0.0233 - val_loss: 5.6828e-04 - val_mae: 0.0080
Epoch 69/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0020 - mae: 0.0224 - val_loss: 7.0041e-04 - val_mae: 0.0098
Epoch 70/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0020 - mae: 0.0228 - val_loss: 5.4175e-04 - val_mae: 0.0080
Epoch 71/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0021 - mae: 0.0235 - val_loss: 5.9499e-04 - val_mae: 0.0084
Epoch 72/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0021 - mae: 0.0228 - val_loss: 5.9959e-04 - val_mae: 0.0093
Epoch 73/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0020 - mae: 0.0222 - val_loss: 7.8957e-04 - val_mae: 0.0100
Epoch 74/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0020 - mae: 0.0223 - val_loss: 5.6444e-04 - val_mae: 0.0084
Epoch 75/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0019 - mae: 0.0222 - val_loss: 6.2403e-04 - val_mae: 0.0089
------Training completed for: CYC_North Strand Rd N B

----------- Evaluating model for: CYC_North Strand Rd N B (5/19)
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step
Evaluation Metrics:
 -RMSE : 5.04
 -MAE  : 4.92
 -MAPE : nan%
 -R²   : 0.0000

--- Processing target 5 out of 19: CYC_Richmond Street Cyclists 1 Merged

Training model for: CYC_Richmond Street Cyclists 1 Merged
Using strategy: _DefaultDistributionStrategy
Epoch 1/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0456 - mae: 0.1285 - val_loss: 0.0422 - val_mae: 0.1277
Epoch 2/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0306 - mae: 0.1022 - val_loss: 0.0360 - val_mae: 0.1206
Epoch 3/100

### **3.5 MODEL SUMMARY**

In [ ]:
for target_name, model in models.items():
    print(f"\n--- Summary for target: {target_name}")
    model.summary()

--- Summary for target: CYC_Clontarf James Larkin Rd

Model: "sequential_19"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_38 (LSTM)                  │ (None, 24, 64)         │        23,296 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_57 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_39 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_58 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_38 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_59 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_39 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 113,673 (444.05 KB)

 Trainable params: 37,889 (148.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 75,784 (296.04 KB)

--- Summary for target: CYC_Clontarf Pebble Beach Carpark

Model: "sequential_20"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_40 (LSTM)                  │ (None, 24, 64)         │        23,296 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_60 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_41 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_61 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_40 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_62 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_41 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 113,673 (444.05 KB)

 Trainable params: 37,889 (148.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 75,784 (296.04 KB)

--- Summary for target: CYC_Grove Road Totem

Model: "sequential_21"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_42 (LSTM)                  │ (None, 24, 64)         │        23,296 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_63 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_43 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_64 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_42 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_65 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_43 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 113,673 (444.05 KB)

 Trainable params: 37,889 (148.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 75,784 (296.04 KB)

--- Summary for target: CYC_North Strand Rd N B

Model: "sequential_22"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_44 (LSTM)                  │ (None, 24, 64)         │        23,296 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_66 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_45 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_67 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_44 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_68 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_45 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 113,673 (444.05 KB)

 Trainable params: 37,889 (148.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 75,784 (296.04 KB)

--- Summary for target: CYC_Richmond Street Cyclists 1 Merged

Model: "sequential_23"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_46 (LSTM)                  │ (None, 24, 64)         │        23,296 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_69 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_47 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_70 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_46 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_71 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_47 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 113,673 (444.05 KB)

 Trainable params: 37,889 (148.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 75,784 (296.04 KB)

--- Summary for target: CYC_Richmond Street Cyclists 2 Merged

Model: "sequential_24"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_48 (LSTM)                  │ (None, 24, 64)         │        23,296 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_72 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_49 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_73 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_48 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_74 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_49 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 113,673 (444.05 KB)

 Trainable params: 37,889 (148.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 75,784 (296.04 KB)

--- Summary for target: FTF_Aston Quay Merged

Model: "sequential_25"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_50 (LSTM)                  │ (None, 24, 64)         │        23,296 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_75 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_51 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_76 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_50 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_77 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_51 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 113,673 (444.05 KB)

 Trainable params: 37,889 (148.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 75,784 (296.04 KB)

--- Summary for target: FTF_Capel St Mary St Merged

Model: "sequential_26"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_52 (LSTM)                  │ (None, 24, 64)         │        23,296 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_78 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_53 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_79 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_52 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_80 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_53 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 113,673 (444.05 KB)

 Trainable params: 37,889 (148.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 75,784 (296.04 KB)

--- Summary for target: FTF_College St Dame St Merged

Model: "sequential_27"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_54 (LSTM)                  │ (None, 24, 64)         │        23,296 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_81 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_55 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_82 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_54 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_83 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_55 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 113,673 (444.05 KB)

 Trainable params: 37,889 (148.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 75,784 (296.04 KB)

--- Summary for target: FTF_Dame St Merged

Model: "sequential_28"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_56 (LSTM)                  │ (None, 24, 64)         │        23,296 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_84 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_57 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_85 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_56 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_86 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_57 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 113,673 (444.05 KB)

 Trainable params: 37,889 (148.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 75,784 (296.04 KB)

--- Summary for target: FTF_Dolier St Burgh Quay Merged

Model: "sequential_29"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_58 (LSTM)                  │ (None, 24, 64)         │        23,296 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_87 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_59 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_88 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_58 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_89 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_59 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 113,673 (444.05 KB)

 Trainable params: 37,889 (148.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 75,784 (296.04 KB)

--- Summary for target: FTF_Grafton St Monsoon Merged

Model: "sequential_30"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_60 (LSTM)                  │ (None, 24, 64)         │        23,296 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_90 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_61 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_91 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_60 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_92 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_61 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 113,673 (444.05 KB)

 Trainable params: 37,889 (148.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 75,784 (296.04 KB)

--- Summary for target: FTF_Grafton St Nassau St Suffolk St

Model: "sequential_31"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_62 (LSTM)                  │ (None, 24, 64)         │        23,296 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_93 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_63 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_94 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_62 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_95 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_63 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 113,673 (444.05 KB)

 Trainable params: 37,889 (148.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 75,784 (296.04 KB)

--- Summary for target: FTF_Henry St Merged

Model: "sequential_32"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_64 (LSTM)                  │ (None, 24, 64)         │        23,296 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_96 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_65 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_97 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_64 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_98 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_65 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 113,673 (444.05 KB)

 Trainable params: 37,889 (148.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 75,784 (296.04 KB)

--- Summary for target: FTF_Mary St Merged

Model: "sequential_33"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_66 (LSTM)                  │ (None, 24, 64)         │        23,296 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_99 (Dropout)            │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_67 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_100 (Dropout)           │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_66 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_101 (Dropout)           │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_67 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 113,673 (444.05 KB)

 Trainable params: 37,889 (148.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 75,784 (296.04 KB)

--- Summary for target: FTF_Oconnell St Princes St North Merged

Model: "sequential_34"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_68 (LSTM)                  │ (None, 24, 64)         │        23,296 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_102 (Dropout)           │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_69 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_103 (Dropout)           │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_68 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_104 (Dropout)           │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_69 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 113,673 (444.05 KB)

 Trainable params: 37,889 (148.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 75,784 (296.04 KB)

--- Summary for target: FTF_Talbot St Guineys Merged

Model: "sequential_35"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_70 (LSTM)                  │ (None, 24, 64)         │        23,296 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_105 (Dropout)           │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_71 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_106 (Dropout)           │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_70 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_107 (Dropout)           │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_71 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 113,673 (444.05 KB)

 Trainable params: 37,889 (148.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 75,784 (296.04 KB)

--- Summary for target: FTF_Westmoreland St East Fleet St Merged

Model: "sequential_36"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_72 (LSTM)                  │ (None, 24, 64)         │        23,296 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_108 (Dropout)           │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_73 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_109 (Dropout)           │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_72 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_110 (Dropout)           │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_73 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 113,673 (444.05 KB)

 Trainable params: 37,889 (148.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 75,784 (296.04 KB)

--- Summary for target: FTF_Westmoreland St West Merged

Model: "sequential_37"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_74 (LSTM)                  │ (None, 24, 64)         │        23,296 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_111 (Dropout)           │ (None, 24, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_75 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_112 (Dropout)           │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_74 (Dense)                │ (None, 64)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_113 (Dropout)           │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_75 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 113,673 (444.05 KB)

 Trainable params: 37,889 (148.00 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 75,784 (296.04 KB)

### **3.6 RESULTS**

In [ ]:
results = pd.DataFrame.from_dict(results, orient="index")
results.index.name = "Target"
results = results.reset_index()

In [ ]:
print("\nSummary of results LSTM with coordinates:")
results

Summary of results LSTM with coordinates:

,Target,RMSE,MAE,MAPE,R2
0,CYC_Clontarf James Larkin Rd,28.038978,21.949563,380.815510,0.468470
1,CYC_Clontarf Pebble Beach Carpark,74.996888,63.048315,657.111993,-0.871702
2,CYC_Grove Road Totem,74.741013,41.915356,144.178066,0.609028
3,CYC_North Strand Rd N B,5.043085,4.923346,NaN,0.000000
4,CYC_Richmond Street Cyclists 1 Merged,46.533369,35.262047,264.490548,-0.016047
5,CYC_Richmond Street Cyclists 2 Merged,37.385669,31.329713,248.341429,0.227783
6,FTF_Aston Quay Merged,3297.920323,3029.949439,594.334387,-6.033072
7,FTF_Capel St Mary St Merged,1146.372930,972.622097,429.910520,-2.713268
8,FTF_College St Dame St Merged,216.142719,143.012360,80.163863,0.738126
9,FTF_Dame St Merged,534.659940,412.412609,356.388842,-1.801352
10,FTF_Dolier St Burgh Quay Merged,1020.770207,970.124719,947.664519,-11.166138
11,FTF_Grafton St Monsoon Merged,772.620936,591.138952,311.951197,0.505918
12,FTF_Grafton St Nassau St Suffolk St,140.710156,95.756180,172.689714,0.619997
13,FTF_Henry St Merged,7152.944119,5214.616728,3547.774543,-18.873644
14,FTF_Mary St Merged,211.234611,158.634832,200.730034,0.802970
15,FTF_Oconnell St Princes St North Merged,709.310253,575.675281,62.100717,-0.550241
16,FTF_Talbot St Guineys Merged,990.263111,946.192634,2834.003631,-9.508883
17,FTF_Westmoreland St East Fleet St Merged,1250.065557,1211.698127,NaN,0.000000
18,FTF_Westmoreland St West Merged,561.279703,457.738452,218.226043,0.033047

### **3.7 PREDICTIONS**

In [ ]:
predictions = {}

for target_name in targets:
    print(f"\nPredicting values for: {target_name}")

    # Test data and targets
    X_test, y_test = test_sets[target_name]
    target_scaler = target_scaler_dict[target_name]

    # Scaled predictions
    y_pred_scaled = models[target_name].predict(X_test)

    # Descale predictions to original values
    y_pred = target_scaler.inverse_transform(y_pred_scaled)
    y_true = target_scaler.inverse_transform(y_test.reshape(-1, 1))

    # DATE AND TIME FROM TEST SET

    # Length used in ltsm sequences
    seq_len = sequence_length

    # Index from start of test set to match the target
    n_total = len(y_lstm_dict[target_name])
    n_train = int(n_total * 0.7)
    n_val   = int(n_total * 0.15)
    start_test_idx = seq_len + n_train + n_val

    datest = data["date and time"].iloc[start_test_idx:].reset_index(drop=True)

    # New DataFrame with values needed for comparison
    predsDataFrame = pd.DataFrame({
        "date and time": datest,
        "Real": y_true.flatten(),
        "LSTM_coords": y_pred.flatten()
    })

    # Round predictions and avoid negative values
    predsDataFrame["LSTM_coords"] = np.round(predsDataFrame["LSTM_coords"]).astype(int)
    predsDataFrame["LSTM_coords"] = predsDataFrame["LSTM_coords"].clip(lower=0)

    predictions[target_name] = predsDataFrame
    print(predsDataFrame.head())

# DataFrame for all predictions
allpreds = pd.concat(
    [dataframe.assign(Target=target) for target, dataframe in predictions.items()],
    ignore_index=True
)

Predicting values for: CYC_Clontarf James Larkin Rd
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
         date and time  Real  LSTM_coords
0  2024-03-07 06:00:00  20.0           25
1  2024-03-07 07:00:00  49.0           35
2  2024-03-07 08:00:00  70.0           43
3  2024-03-07 09:00:00  51.0           43
4  2024-03-07 10:00:00  31.0           38

Predicting values for: CYC_Clontarf Pebble Beach Carpark
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
         date and time   Real  LSTM_coords
0  2024-03-07 06:00:00   26.0           63
1  2024-03-07 07:00:00   75.0           84
2  2024-03-07 08:00:00  105.0           97
3  2024-03-07 09:00:00   75.0           95
4  2024-03-07 10:00:00   33.0           82

Predicting values for: CYC_Grove Road Totem
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
         date and time   Real  LSTM_coords
0  2024-03-07 06:00:00  125.0           53
1  2024-03-07 07:00:00  309.0          160
2  2024-03-07 08:00:00  607.0          286
3  2024-03-07 09:00:00  247.0          117
4  2024-03-07 10:00:00   94.0          101

Predicting values for: CYC_North Strand Rd N B
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
         date and time  Real  LSTM_coords
0  2024-03-07 06:00:00   0.0            0
1  2024-03-07 07:00:00   0.0            0
2  2024-03-07 08:00:00   0.0            0
3  2024-03-07 09:00:00   0.0            0
4  2024-03-07 10:00:00   0.0            0

Predicting values for: CYC_Richmond Street Cyclists 1 Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
         date and time   Real  LSTM_coords
0  2024-03-07 06:00:00   21.0           86
1  2024-03-07 07:00:00   88.0          101
2  2024-03-07 08:00:00  244.0          110
3  2024-03-07 09:00:00  135.0          113
4  2024-03-07 10:00:00   75.0          114

Predicting values for: CYC_Richmond Street Cyclists 2 Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
         date and time  Real  LSTM_coords
0  2024-03-07 06:00:00  12.0           39
1  2024-03-07 07:00:00  38.0           58
2  2024-03-07 08:00:00  53.0           70
3  2024-03-07 09:00:00  37.0           73
4  2024-03-07 10:00:00  19.0           70

Predicting values for: FTF_Aston Quay Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
         date and time    Real  LSTM_coords
0  2024-03-07 06:00:00  1524.0         2450
1  2024-03-07 07:00:00  2191.0         2604
2  2024-03-07 08:00:00  4623.0         2916
3  2024-03-07 09:00:00  3941.0         3316
4  2024-03-07 10:00:00  2430.0         3760

Predicting values for: FTF_Capel St Mary St Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
         date and time         Real  LSTM_coords
0  2024-03-07 06:00:00   347.999969          440
1  2024-03-07 07:00:00   305.000000          525
2  2024-03-07 08:00:00  1026.000000          808
3  2024-03-07 09:00:00  1098.000000         1358
4  2024-03-07 10:00:00  1721.000000         1997

Predicting values for: FTF_College St Dame St Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
         date and time         Real  LSTM_coords
0  2024-03-07 06:00:00   250.000000          162
1  2024-03-07 07:00:00   533.000000          556
2  2024-03-07 08:00:00  1243.000000          763
3  2024-03-07 09:00:00   966.000061          801
4  2024-03-07 10:00:00   809.000000          803

Predicting values for: FTF_Dame St Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
         date and time        Real  LSTM_coords
0  2024-03-07 06:00:00  293.000000          269
1  2024-03-07 07:00:00  480.000000          332
2  2024-03-07 08:00:00  663.000000          437
3  2024-03-07 09:00:00  702.000061          562
4  2024-03-07 10:00:00  596.000000          712

Predicting values for: FTF_Dolier St Burgh Quay Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
         date and time        Real  LSTM_coords
0  2024-03-07 06:00:00  291.000000          722
1  2024-03-07 07:00:00  493.999969          790
2  2024-03-07 08:00:00  822.999939          930
3  2024-03-07 09:00:00  752.000061         1085
4  2024-03-07 10:00:00  535.000000         1224

Predicting values for: FTF_Grafton St Monsoon Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
         date and time         Real  LSTM_coords
0  2024-03-07 06:00:00  1866.999878          328
1  2024-03-07 07:00:00  1909.000000          369
2  2024-03-07 08:00:00  1718.000000          482
3  2024-03-07 09:00:00  2174.000000          749
4  2024-03-07 10:00:00  2111.000000         1154

Predicting values for: FTF_Grafton St Nassau St Suffolk St
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
         date and time   Real  LSTM_coords
0  2024-03-07 06:00:00   76.0           97
1  2024-03-07 07:00:00  162.0          150
2  2024-03-07 08:00:00  469.0          218
3  2024-03-07 09:00:00  330.0          281
4  2024-03-07 10:00:00  273.0          345

Predicting values for: FTF_Henry St Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
         date and time    Real  LSTM_coords
0  2024-03-07 06:00:00   458.0         1018
1  2024-03-07 07:00:00   925.0         1453
2  2024-03-07 08:00:00  2353.0         2198
3  2024-03-07 09:00:00  3062.0         3354
4  2024-03-07 10:00:00  4369.0         5496

Predicting values for: FTF_Mary St Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
         date and time        Real  LSTM_coords
0  2024-03-07 06:00:00   58.999996           92
1  2024-03-07 07:00:00   87.000000          116
2  2024-03-07 08:00:00  286.000000          175
3  2024-03-07 09:00:00  334.000000          313
4  2024-03-07 10:00:00  918.000000          496

Predicting values for: FTF_Oconnell St Princes St North Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
         date and time    Real  LSTM_coords
0  2024-03-07 06:00:00   366.0          312
1  2024-03-07 07:00:00   598.0          510
2  2024-03-07 08:00:00  1050.0          678
3  2024-03-07 09:00:00   760.0          782
4  2024-03-07 10:00:00   720.0          858

Predicting values for: FTF_Talbot St Guineys Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
         date and time  Real  LSTM_coords
0  2024-03-07 06:00:00   0.0         1032
1  2024-03-07 07:00:00   0.0         1034
2  2024-03-07 08:00:00   0.0         1054
3  2024-03-07 09:00:00   0.0         1075
4  2024-03-07 10:00:00   0.0         1116

Predicting values for: FTF_Westmoreland St East Fleet St Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
         date and time  Real  LSTM_coords
0  2024-03-07 06:00:00   0.0         1286
1  2024-03-07 07:00:00   0.0         1290
2  2024-03-07 08:00:00   0.0         1291
3  2024-03-07 09:00:00   0.0         1298
4  2024-03-07 10:00:00   0.0         1294

Predicting values for: FTF_Westmoreland St West Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
         date and time   Real  LSTM_coords
0  2024-03-07 06:00:00  325.0          575
1  2024-03-07 07:00:00  594.0          579
2  2024-03-07 08:00:00  934.0          597
3  2024-03-07 09:00:00  833.0          616
4  2024-03-07 10:00:00  930.0          640

In [ ]:
allpreds.head(20)

          date and time  Real  LSTM_coords                        Target
0   2024-03-07 06:00:00  20.0           25  CYC_Clontarf James Larkin Rd
1   2024-03-07 07:00:00  49.0           35  CYC_Clontarf James Larkin Rd
2   2024-03-07 08:00:00  70.0           43  CYC_Clontarf James Larkin Rd
3   2024-03-07 09:00:00  51.0           43  CYC_Clontarf James Larkin Rd
4   2024-03-07 10:00:00  31.0           38  CYC_Clontarf James Larkin Rd
5   2024-03-07 11:00:00  32.0           36  CYC_Clontarf James Larkin Rd
6   2024-03-07 12:00:00  36.0           37  CYC_Clontarf James Larkin Rd
7   2024-03-07 13:00:00  33.0           39  CYC_Clontarf James Larkin Rd
8   2024-03-07 14:00:00  23.0           42  CYC_Clontarf James Larkin Rd
9   2024-03-07 15:00:00  25.0           45  CYC_Clontarf James Larkin Rd
10  2024-03-07 16:00:00  39.0           49  CYC_Clontarf James Larkin Rd
11  2024-03-07 17:00:00  68.0           52  CYC_Clontarf James Larkin Rd
12  2024-03-07 18:00:00  62.0           55  CYC_Clontarf James Larkin Rd
13  2024-03-07 19:00:00  33.0           48  CYC_Clontarf James Larkin Rd
14  2024-03-07 20:00:00   8.0           32  CYC_Clontarf James Larkin Rd
15  2024-03-07 21:00:00   7.0           17  CYC_Clontarf James Larkin Rd
16  2024-03-07 22:00:00   6.0            9  CYC_Clontarf James Larkin Rd
17  2024-03-07 23:00:00   1.0            6  CYC_Clontarf James Larkin Rd
18  2024-03-08 00:00:00   4.0            5  CYC_Clontarf James Larkin Rd
19  2024-03-08 01:00:00   2.0            5  CYC_Clontarf James Larkin Rd

# **4. RESULTS TO AZURE BLOB STORAGE**

In [ ]:
def save_blob(data, filename):
    try:
        blob_name = f"{CONTAINER_NAME}/{filename}"
        csv_data = data.to_csv(index=False)
        with fs.open(blob_name, "w") as f:
            f.write(csv_data)
        print(f"Saved to {blob_name}")
    except Exception as e:
        print(f"Error saving data to blob storage: {str(e)}")
        return False

In [ ]:
CONTAINER_NAME = "results"

save_blob(results, "rlstm_coords.csv")

Saved to results/rlstm_coords.csv

In [ ]:
CONTAINER_NAME = "predictions"

save_blob(allpreds, "pred_lstm_coords.csv")

Saved to predictions/pred_lstm_coords.csv