# **DEEP LEARNING MODELLING: CNN-LSTM WITHOUT GEOGRAPHICAL COORDINATES**

## **1. LIBRARIES**

### **1.1 DEPENDENCIES**

In [ ]:
! pip install adlfs azure-storage-blob
! pip install tensorflow
! pip install tqdm

Collecting adlfs
  Downloading adlfs-2024.12.0-py3-none-any.whl.metadata (7.7 kB)
Collecting azure-storage-blob
  Downloading azure_storage_blob-12.26.0-py3-none-any.whl.metadata (26 kB)
Collecting azure-core<2.0.0,>=1.28.0 (from adlfs)
  Downloading azure_core-1.35.0-py3-none-any.whl.metadata (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.4/44.4 kB 2.1 MB/s eta 0:00:00
Collecting azure-datalake-store<0.1,>=0.0.53 (from adlfs)
  Downloading azure_datalake_store-0.0.53-py2.py3-none-any.whl.metadata (19 kB)
Collecting azure-identity (from adlfs)
  Downloading azure_identity-1.24.0-py3-none-any.whl.metadata (86 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 kB 4.5 MB/s eta 0:00:00
Requirement already satisfied: fsspec>=2023.12.0 in /usr/local/lib/python3.11/dist-packages (from adlfs) (2025.3.0)
Requirement already satisfied: aiohttp>=3.7.0 in /usr/local/lib/python3.11/dist-packages (from adlfs) (3.12.15)
Requirement already satisfied: cryptography>=2.1.4 in /usr/local/lib/python3.11/dist-packages (from azure-storage-blob) (43.0.3)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from azure-storage-blob) (4.14.1)
Collecting isodate>=0.6.1 (from azure-storage-blob)
  Downloading isodate-0.7.2-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (6.6.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.0->adlfs) (1.20.1)
Requirement already satisfied: requests>=2.21.0 in /usr/local/lib/python3.11/dist-packages (from azure-core<2.0.0,>=1.28.0->adlfs) (2.32.3)
Requirement already satisfied: six>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from azure-core<2.0.0,>=1.28.0->adlfs) (1.17.0)
Requirement already satisfied: cffi in /usr/local/lib/python3.11/dist-packages (from azure-datalake-store<0.1,>=0.0.53->adlfs) (1.17.1)
Collecting msal<2,>=1.16.0 (from azure-datalake-store<0.1,>=0.0.53->adlfs)
  Downloading msal-1.33.0-py3-none-any.whl.metadata (11 kB)
Collecting msal-extensions>=1.2.0 (from azure-identity->adlfs)
  Downloading msal_extensions-1.3.1-py3-none-any.whl.metadata (7.8 kB)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi->azure-datalake-store<0.1,>=0.0.53->adlfs) (2.22)
Requirement already satisfied: PyJWT<3,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from PyJWT[crypto]<3,>=1.0.0->msal<2,>=1.16.0->azure-datalake-store<0.1,>=0.0.53->adlfs) (2.10.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.21.0->azure-core<2.0.0,>=1.28.0->adlfs) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.21.0->azure-core<2.0.0,>=1.28.0->adlfs) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.21.0->azure-core<2.0.0,>=1.28.0->adlfs) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.21.0->azure-core<2.0.0,>=1.28.0->adlfs) (2025.8.3)
Downloading adlfs-2024.12.0-py3-none-any.whl (41 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.8/41.8 kB 4.2 MB/s eta 0:00:00
Downloading azure_storage_blob-12.26.0-py3-none-any.whl (412 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 412.9/412.9 kB 17.2 MB/s eta 0:00:00
Downloading azure_core-1.35.0-py3-none-any.whl (210 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 210.7/210.7 kB 22.4 MB/s eta 0:00:00
Downloading azure_datalake_store-0.0.53-py2.py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.3/55.3 kB 6.2 MB/s eta 0:00:00
Downloading isodate-0.7.2-py3-none-any.whl (22 kB)
Downloading azure_identity-1.24.0-py3-none-any.whl (187 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 187.9/187.9 kB 20.0 MB/s eta 0:00:00
Downloading msal-1.33.0-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.9/116.9 kB 12.5 MB/s eta 0:00:00
Downloading msal_extensions-1.3.1-py3-none-any.whl (20 kB)
Installing collected packages: isodate, azure-core, azure-storage-blob, msal, msal-extensions, azure-datalake-store, azure-identity, adlfs
Successfully installed adlfs-2024.12.0 azure-core-1.35.0 azure-datalake-store-0.0.53 azure-identity-1.24.0 azure-storage-blob-12.26.0 isodate-0.7.2 msal-1.33.0 msal-extensions-1.3.1
Requirement already satisfied: tensorflow in /usr/local/lib/python3.11/dist-packages (2.19.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (25.2.10)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from tensorflow) (25.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (5.29.5)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (2.32.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.1.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (4.14.1)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.17.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (1.74.0)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.10.0)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.5.3)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow) (0.37.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in /usr/local/lib/python3.11/dist-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.11/dist-packages (from keras>=3.5.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.11/dist-packages (from keras>=3.5.0->tensorflow) (0.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorflow) (2025.8.3)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.11/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.8.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from tensorboard~=2.19.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.1.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.11/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow) (3.0.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.5.0->tensorflow) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.5.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (4.67.1)

### **1.2 LIBRARIES**

In [ ]:
# STANDARD LIBRARY
import os
import io
import random

# DATA MANIPULATION AND ANALYSIS
import pandas as pd
import numpy as np

# DATA VISUALISATION
import matplotlib.pyplot as plt
import seaborn as sns

# AZURE CLOUD STORAGE
from adlfs import AzureBlobFileSystem
from azure.storage.blob import BlobServiceClient

# REGULAR EXPRESSIONS
import re

# TIME SERIES
from sklearn.model_selection import TimeSeriesSplit

# STANDARIZATION
from sklearn.preprocessing import StandardScaler

# EVALUATION METRICS
from sklearn.metrics import r2_score

# PROGRESS BAR
from tqdm import tqdm

# TENSORFLOW
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, LSTM, Dense, Dropout
from tensorflow.keras import regularizers
from tensorflow.keras.layers import Conv1D, BatchNormalization, Dropout, LSTM, Dense, Input
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras import regularizers
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import mixed_precision
mixed_precision.set_global_policy("mixed_float16")
from sklearn.preprocessing import RobustScaler
from tensorflow.keras.losses import Huber

# SEED
np.random.seed(42)
tf.random.set_seed(42)
random.seed(42)

In [ ]:
print(tf.__version__)

2.19.0

In [ ]:
# Correctly set pandas display option for max columns and rows
pd.options.display.max_columns = None
pd.options.display.max_rows = None

## **2. LOADING DATASETS FROM AZURE BLOB STORAGE**

In [ ]:
def load_csv_from_blob(blob_name):
    blob_client = container_client.get_blob_client(blob_name)
    stream = blob_client.download_blob()
    data_bytes = stream.readall()
    data_str = data_bytes.decode("utf-8")
    return pd.read_csv(io.StringIO(data_str))


# Connection configuration
AZURE_STORAGE_ACCOUNT = "researchprojectx24104515"
AZURE_STORAGE_KEY = "bxpexO6i+Hz6n1WiipTn+sTCuLPGMS1BogMERrIrHd16DpQ0GLfQ0R33yrSw4MxsDomq5yNMgw1o+AStlx/MjA=="
connection_string = f"DefaultEndpointsProtocol=https;AccountName={AZURE_STORAGE_ACCOUNT};AccountKey={AZURE_STORAGE_KEY};EndpointSuffix=core.windows.net"
blob_service_client = BlobServiceClient.from_connection_string(connection_string)

fs = AzureBlobFileSystem(
    account_name=AZURE_STORAGE_ACCOUNT,
    account_key=AZURE_STORAGE_KEY
)

In [ ]:
# Establish connection to cycle
CONTAINER_NAME = "preprocessed"
container_client = blob_service_client.get_container_client(CONTAINER_NAME)

file_name = "preprocessed.csv"
data = load_csv_from_blob(file_name)
print(f"Loaded '{file_name}' with shape: {data.shape}")

Loaded 'preprocessed.csv' with shape: (53424, 44)

In [ ]:
# Interaction features created with weather features
interactionf = ["WTH_dew_spread", "WTH_prob_cond", "WTH_severe"]

# Using regex to get all temporal and weather prefix patterns
temp_pattern = re.compile(r"^TEMP_")
wth_patterb = re.compile(r"^WTH_")

# Using regex to get all temporal and weather features
temporalf = [col for col in data.columns if temp_pattern.match(col)]
weatherf = [col for col in data.columns if wth_patterb.match(col) and col not in interactionf]

# Combine all features
fcolumns = weatherf + temporalf + interactionf

# Extract cycle and footfall targets
cycle_t = [col for col in data.columns if col.startswith("CYC_")]
footfall_t = [col for col in data.columns if col.startswith("FTF_")]
targets = cycle_t + footfall_t

# Prepare feature matrix
X = data[fcolumns].copy()
y = data[targets].copy()

# Handle missing values
X = X.ffill().bfill()
y = y.fillna(0)

print(f"Features shape: {X.shape}")
print(f"Targets shape: {y.shape}")
print(f"Feature columns: {len(fcolumns)}")

Features shape: (53424, 24)
Targets shape: (53424, 19)
Feature columns: 24

## **3. CNN / LSTM**

### **3.1 DEFINE CNN-LSTM SEQUENCES AND TIME SERIES SPLIT**

In [ ]:
# CNN-LSTM sequences
def cnnlstm_seqs(data, targets, features, seq_len=24):

    # Scale all features
    f_scaler = MinMaxScaler()
    features_scaled = f_scaler.fit_transform(data[features])

    # Containers for results
    X_data = {}
    y_data = {}
    t_scalers = {}

    # Processing separately each target
    for t in targets:
        # Extract target column and reshape to 2D
        y = data[t].values.reshape(-1, 1)

        # Fitting a scaler
        t_scaler = MinMaxScaler()
        y_scaled = t_scaler.fit_transform(y)
        X, y_seq = [], []

        # Creating sequences of length
        for i in range(seq_len, len(features_scaled)):
            seq = features_scaled[i-seq_len:i]
            X.append(seq)
            y_seq.append(y_scaled[i])

        # Converting data to NumPy arrays to store in dictionaries
        X_data[t] = np.array(X, dtype=np.float32)
        y_data[t] = np.array(y_seq, dtype=np.float32)
        t_scalers[t] = t_scaler

    return X_data, y_data, f_scaler, t_scalers

# Time Series Split
def ts_split(X, y, train_ratio=0.7, val_ratio=0.15):

    # Total number of sequences
    n_samples = len(X)

    # Index boundaeries calculated by ratios
    train_end = int(n_samples * train_ratio)
    val_end = int(n_samples * (train_ratio + val_ratio))

    # Slice sets sequentially as a Time Series
    X_train = X[:train_end]
    y_train = y[:train_end]
    X_val = X[train_end:val_end]
    y_val = y[train_end:val_end]
    X_test = X[val_end:]
    y_test = y[val_end:]

    return X_train, X_val, X_test, y_train, y_val, y_test

### **3.2 BUILD CNN-LSTM MODEL**

In [ ]:
def build_cnnlstm(input_shape=(24, 24), conv_filters=64, lstm_units=64, dense_units=64, dropout_rate=0.2):
    # Level 2 regularisation
    reg = 1e-4

    # Batch Normalization for Training stabilisation and Dropout to avoid overfitting

    # Model
    model = Sequential()
    model.add(Input(shape=input_shape))

    # FEATURE EXTRACTION

    # First convolutional layer for feature extraction from short-term sequential data
    model.add(Conv1D(conv_filters, 3, activation="relu", padding="same",
                     kernel_regularizer=regularizers.l2(reg)))
    model.add(BatchNormalization())
    model.add(Dropout(dropout_rate))

    # Second convolutional layer for more abstract features and long-term temporal patterns
    model.add(Conv1D(conv_filters//2, 5, activation="relu", padding="same",
                     kernel_regularizer=regularizers.l2(reg)))
    model.add(BatchNormalization())
    model.add(Dropout(dropout_rate))

    # LSTM FOR LONG TERM DEPENDENCIES

    # First LSTM layer, returns to a sequence that keeps temporal information
    model.add(LSTM(lstm_units, return_sequences=True, dropout=dropout_rate, recurrent_dropout=dropout_rate,
                   kernel_regularizer=regularizers.l2(reg)))
    model.add(Dropout(dropout_rate))

    # Second LSTM layer, returns to a single output
    model.add(LSTM(lstm_units//2, return_sequences=False, dropout=dropout_rate, recurrent_dropout=dropout_rate,
                   kernel_regularizer=regularizers.l2(reg)))
    model.add(Dropout(dropout_rate))

    # Dense layer for learned features before final prediction
    model.add(Dense(dense_units, activation="relu", kernel_regularizer=regularizers.l2(reg)))
    model.add(Dropout(dropout_rate))

    # Single output neuron with no negative predictions
    model.add(Dense(1, activation="relu"))

    # Model compilation
    model.compile(
        optimizer=Adam(learning_rate=0.001),
        loss=Huber(delta=1.0),
        metrics=["mae"]
    )
    return model

### **3.3 TRAIN MODEL**

In [ ]:
# TRAIN MODEL
def train_cnnlstm(target_name, X, y, callbacks=None):

    # Training starts
    print(f"\nTraining model for: {target_name} ===")

    # Split the sequences into train, test and validation sets
    X_train, X_val, X_test, y_train, y_val, y_test = ts_split(X, y)

    # CNN-LSTM model built with an input shape that matches the sequences
    model = build_cnnlstm(input_shape=X_train.shape[1:])

    # If not callbacks provided, use this as default
    if callbacks is None:
        # Stop if validation loss stops improving for 10 epochs
        early_stopping = EarlyStopping(monitor="val_loss", patience=10, restore_best_weights=True)
        # Reduce learning rate if validation loss doe not improve after 5 epochs
        reduce_lr = ReduceLROnPlateau(monitor="val_loss", factor=0.5, patience=5, min_lr=1e-6)
        callbacks = [early_stopping, reduce_lr]

    # Train the model
    history = model.fit(
        X_train, y_train,
        # Maximum training Epochs
        epochs=100,
        # Large batch size for training efficiency
        batch_size=1024,
        # Monitor performance on validation set
        validation_data=(X_val, y_val),
        # Apply early stop or reduce learning rate
        callbacks=callbacks,
        # Shows training process
        verbose=1
    )

    print(f"------Training completed for: {target_name}")
    return model, history, X_test, y_test

### **3.4 EVALUTAION**

In [ ]:
# EVALUATE MODEL
def evaluate_mtarget(model, X_test, y_test, target_scaler, target_name, target_idx, n_targets):
    print(f"\n----- Evaluating model for: {target_name} ({target_idx + 1}/{n_targets})")

    y_pred = model.predict(X_test)

    # Inverse transfomation of y_pred and predictions
    y_true = target_scaler.inverse_transform(y_test.reshape(-1, 1))
    y_pred = target_scaler.inverse_transform(y_pred)

    # Round to whole numbers
    y_pred = np.round(y_pred).astype(int)
    y_true = np.round(y_true).astype(int)

    rmse = np.sqrt(np.mean((y_true - y_pred) ** 2))
    mae = np.mean(np.abs(y_true - y_pred))
    mask = y_true != 0
    mape = np.mean(np.abs((y_true[mask] - y_pred[mask]) / y_true[mask])) * 100 if np.any(mask) else np.nan
    r2 = r2_score(y_true, y_pred)

    print("Evaluation Metrics:")
    print(f" -RMSE : {rmse:.2f}")
    print(f" -MAE  : {mae:.2f}")
    print(f" -MAPE : {mape:.2f}%")
    print(f" -R²   : {r2:.4f}")

    return {
        "RMSE": rmse,
        "MAE": mae,
        "MAPE": mape,
        "R2": r2
    }

### **3.5 APPLYING CNN-LSTM**

In [ ]:
# APPLY CNN LSTM

# Number of time steps per sequence
sequence_length = 24

# Prepare CNN-LSTM sequences (features for each timestep)
X_cnn_lstm_dict, y_cnn_lstm_dict, feature_scaler_lstm, target_scaler_dict = cnnlstm_seqs(
    # Combines features (X) with targets (Y) into a DataFrames
    pd.concat([X, y], axis=1),
    targets,
    fcolumns,
    sequence_length
)

# Shape of sequence
print("Shape of a sequence with coordinates:", X_cnn_lstm_dict[targets[0]].shape)

# Dictionaries to store results for all targets
trained_models = {}
histories = {}
results = {}
test_sets = {}

# Total number of target variables
n_targets = len(targets)

# Train and evaluate model for each target
for idx, target_name in enumerate(targets, 1):
    print(f"\n--- Processing target {idx} out of {n_targets}: {target_name}")

    # Retrieve the prepared sequences for this target
    X_data = X_cnn_lstm_dict[target_name]
    y_data = y_cnn_lstm_dict[target_name]

    # Train the model with early stopping
    model, history, X_test, y_test = train_cnnlstm(
        target_name,
        X_data,
        y_data,
        callbacks=[EarlyStopping(monitor="val_loss", patience=5, restore_best_weights=True)]
    )

    # Store the trained models and training history
    trained_models[target_name] = model
    histories[target_name] = history

    # Store the test set for this target
    test_sets[target_name] = (X_test, y_test)

    # Get the scaler for this target (for inverse transformation of predictions)
    target_scaler = target_scaler_dict[target_name]

    # Evaluate the performance of the model on test set
    metrics = evaluate_mtarget(
        model,
        X_test,
        y_test,
        target_scaler,
        target_name,
        idx,
        n_targets
    )

    # Save the metrics for the evaluated target
    results[target_name] = metrics

print("\nTraining and evaluation completed for all targets.")

Shape of a sequence with coordinates: (53400, 24, 24)

--- Processing target 1 out of 19: CYC_Clontarf James Larkin Rd

Training model for: CYC_Clontarf James Larkin Rd ===
Epoch 1/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 19s 157ms/step - loss: 0.0282 - mae: 0.0467 - val_loss: 0.0218 - val_mae: 0.0531
Epoch 2/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0185 - mae: 0.0307 - val_loss: 0.0145 - val_mae: 0.0465
Epoch 3/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 121ms/step - loss: 0.0125 - mae: 0.0251 - val_loss: 0.0106 - val_mae: 0.0463
Epoch 4/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0086 - mae: 0.0208 - val_loss: 0.0080 - val_mae: 0.0492
Epoch 5/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0061 - mae: 0.0182 - val_loss: 0.0065 - val_mae: 0.0509
Epoch 6/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 117ms/step - loss: 0.0045 - mae: 0.0175 - val_loss: 0.0053 - val_mae: 0.0529
Epoch 7/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0034 - mae: 0.0163 - val_loss: 0.0045 - val_mae: 0.0516
Epoch 8/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0027 - mae: 0.0160 - val_loss: 0.0040 - val_mae: 0.0538
Epoch 9/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0021 - mae: 0.0153 - val_loss: 0.0035 - val_mae: 0.0538
Epoch 10/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 117ms/step - loss: 0.0019 - mae: 0.0169 - val_loss: 0.0030 - val_mae: 0.0450
Epoch 11/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 117ms/step - loss: 0.0016 - mae: 0.0152 - val_loss: 0.0029 - val_mae: 0.0523
Epoch 12/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0014 - mae: 0.0155 - val_loss: 0.0026 - val_mae: 0.0458
Epoch 13/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 118ms/step - loss: 0.0013 - mae: 0.0154 - val_loss: 0.0023 - val_mae: 0.0428
Epoch 14/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 118ms/step - loss: 0.0012 - mae: 0.0144 - val_loss: 0.0020 - val_mae: 0.0369
Epoch 15/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 117ms/step - loss: 0.0010 - mae: 0.0142 - val_loss: 0.0022 - val_mae: 0.0427
Epoch 16/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 116ms/step - loss: 9.8862e-04 - mae: 0.0143 - val_loss: 0.0016 - val_mae: 0.0306
Epoch 17/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 9.6247e-04 - mae: 0.0145 - val_loss: 0.0019 - val_mae: 0.0320
Epoch 18/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 117ms/step - loss: 9.2964e-04 - mae: 0.0142 - val_loss: 0.0016 - val_mae: 0.0327
Epoch 19/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 117ms/step - loss: 9.6036e-04 - mae: 0.0148 - val_loss: 0.0016 - val_mae: 0.0321
Epoch 20/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0011 - mae: 0.0166 - val_loss: 0.0018 - val_mae: 0.0309
Epoch 21/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 117ms/step - loss: 0.0011 - mae: 0.0159 - val_loss: 0.0020 - val_mae: 0.0348
Epoch 22/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 121ms/step - loss: 9.4396e-04 - mae: 0.0144 - val_loss: 0.0016 - val_mae: 0.0303
Epoch 23/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 117ms/step - loss: 8.8293e-04 - mae: 0.0142 - val_loss: 9.7244e-04 - val_mae: 0.0228
Epoch 24/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 118ms/step - loss: 8.1851e-04 - mae: 0.0136 - val_loss: 0.0011 - val_mae: 0.0255
Epoch 25/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 8.6531e-04 - mae: 0.0144 - val_loss: 0.0014 - val_mae: 0.0276
Epoch 26/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 118ms/step - loss: 8.5105e-04 - mae: 0.0145 - val_loss: 9.4313e-04 - val_mae: 0.0226
Epoch 27/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 118ms/step - loss: 7.7998e-04 - mae: 0.0137 - val_loss: 0.0010 - val_mae: 0.0235
Epoch 28/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 8.4153e-04 - mae: 0.0146 - val_loss: 0.0012 - val_mae: 0.0258
Epoch 29/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 118ms/step - loss: 8.5228e-04 - mae: 0.0146 - val_loss: 9.5981e-04 - val_mae: 0.0226
Epoch 30/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 8.0009e-04 - mae: 0.0140 - val_loss: 0.0011 - val_mae: 0.0248
Epoch 31/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 118ms/step - loss: 7.6747e-04 - mae: 0.0139 - val_loss: 0.0010 - val_mae: 0.0246
------Training completed for: CYC_Clontarf James Larkin Rd

----- Evaluating model for: CYC_Clontarf James Larkin Rd (2/19)
251/251 ━━━━━━━━━━━━━━━━━━━━ 7s 25ms/step
Evaluation Metrics:
 -RMSE : 18.88
 -MAE  : 11.72
 -MAPE : 62.21%
 -R²   : 0.7589

--- Processing target 2 out of 19: CYC_Clontarf Pebble Beach Carpark

Training model for: CYC_Clontarf Pebble Beach Carpark ===
Epoch 1/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 14s 158ms/step - loss: 0.0278 - mae: 0.0435 - val_loss: 0.0204 - val_mae: 0.0500
Epoch 2/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0179 - mae: 0.0296 - val_loss: 0.0169 - val_mae: 0.0673
Epoch 3/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 121ms/step - loss: 0.0117 - mae: 0.0235 - val_loss: 0.0128 - val_mae: 0.0664
Epoch 4/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 118ms/step - loss: 0.0078 - mae: 0.0188 - val_loss: 0.0098 - val_mae: 0.0602
Epoch 5/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0055 - mae: 0.0177 - val_loss: 0.0084 - val_mae: 0.0606
Epoch 6/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0041 - mae: 0.0174 - val_loss: 0.0070 - val_mae: 0.0573
Epoch 7/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0031 - mae: 0.0162 - val_loss: 0.0063 - val_mae: 0.0578
Epoch 8/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0024 - mae: 0.0159 - val_loss: 0.0056 - val_mae: 0.0550
Epoch 9/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0021 - mae: 0.0161 - val_loss: 0.0043 - val_mae: 0.0496
Epoch 10/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 118ms/step - loss: 0.0018 - mae: 0.0158 - val_loss: 0.0045 - val_mae: 0.0501
Epoch 11/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 121ms/step - loss: 0.0015 - mae: 0.0150 - val_loss: 0.0035 - val_mae: 0.0448
Epoch 12/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0014 - mae: 0.0153 - val_loss: 0.0032 - val_mae: 0.0423
Epoch 13/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0013 - mae: 0.0152 - val_loss: 0.0033 - val_mae: 0.0431
Epoch 14/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 121ms/step - loss: 0.0012 - mae: 0.0149 - val_loss: 0.0028 - val_mae: 0.0394
Epoch 15/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0010 - mae: 0.0144 - val_loss: 0.0026 - val_mae: 0.0378
Epoch 16/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0011 - mae: 0.0150 - val_loss: 0.0021 - val_mae: 0.0357
Epoch 17/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 118ms/step - loss: 0.0010 - mae: 0.0148 - val_loss: 0.0024 - val_mae: 0.0359
Epoch 18/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 9.0288e-04 - mae: 0.0139 - val_loss: 0.0018 - val_mae: 0.0339
Epoch 19/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 8.8019e-04 - mae: 0.0141 - val_loss: 0.0021 - val_mae: 0.0476
Epoch 20/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 118ms/step - loss: 0.0010 - mae: 0.0157 - val_loss: 0.0015 - val_mae: 0.0276
Epoch 21/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 121ms/step - loss: 9.2916e-04 - mae: 0.0144 - val_loss: 0.0017 - val_mae: 0.0300
Epoch 22/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 8.6751e-04 - mae: 0.0138 - val_loss: 0.0013 - val_mae: 0.0290
Epoch 23/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 8.6216e-04 - mae: 0.0143 - val_loss: 0.0015 - val_mae: 0.0281
Epoch 24/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 121ms/step - loss: 7.7670e-04 - mae: 0.0135 - val_loss: 0.0019 - val_mae: 0.0335
Epoch 25/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 118ms/step - loss: 7.6855e-04 - mae: 0.0135 - val_loss: 0.0016 - val_mae: 0.0294
Epoch 26/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 8.1134e-04 - mae: 0.0139 - val_loss: 0.0012 - val_mae: 0.0279
Epoch 27/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 7.8873e-04 - mae: 0.0141 - val_loss: 0.0015 - val_mae: 0.0312
Epoch 28/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 7.7174e-04 - mae: 0.0137 - val_loss: 0.0024 - val_mae: 0.0409
Epoch 29/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 7.8706e-04 - mae: 0.0140 - val_loss: 0.0016 - val_mae: 0.0316
Epoch 30/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 117ms/step - loss: 9.3270e-04 - mae: 0.0154 - val_loss: 0.0017 - val_mae: 0.0356
Epoch 31/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 118ms/step - loss: 8.5484e-04 - mae: 0.0143 - val_loss: 0.0012 - val_mae: 0.0266
------Training completed for: CYC_Clontarf Pebble Beach Carpark

----- Evaluating model for: CYC_Clontarf Pebble Beach Carpark (3/19)
251/251 ━━━━━━━━━━━━━━━━━━━━ 7s 25ms/step
Evaluation Metrics:
 -RMSE : 27.76
 -MAE  : 17.82
 -MAPE : 88.26%
 -R²   : 0.7435

--- Processing target 3 out of 19: CYC_Grove Road Totem

Training model for: CYC_Grove Road Totem ===
Epoch 1/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 14s 148ms/step - loss: 0.0317 - mae: 0.0789 - val_loss: 0.0247 - val_mae: 0.0612
Epoch 2/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0212 - mae: 0.0521 - val_loss: 0.0176 - val_mae: 0.0568
Epoch 3/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0151 - mae: 0.0425 - val_loss: 0.0137 - val_mae: 0.0631
Epoch 4/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 118ms/step - loss: 0.0110 - mae: 0.0375 - val_loss: 0.0113 - val_mae: 0.0648
Epoch 5/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0083 - mae: 0.0342 - val_loss: 0.0095 - val_mae: 0.0643
Epoch 6/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0064 - mae: 0.0317 - val_loss: 0.0084 - val_mae: 0.0673
Epoch 7/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0052 - mae: 0.0305 - val_loss: 0.0073 - val_mae: 0.0643
Epoch 8/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0043 - mae: 0.0293 - val_loss: 0.0064 - val_mae: 0.0656
Epoch 9/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0036 - mae: 0.0283 - val_loss: 0.0058 - val_mae: 0.0596
Epoch 10/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0032 - mae: 0.0287 - val_loss: 0.0052 - val_mae: 0.0609
Epoch 11/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0027 - mae: 0.0272 - val_loss: 0.0047 - val_mae: 0.0585
Epoch 12/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0024 - mae: 0.0268 - val_loss: 0.0043 - val_mae: 0.0566
Epoch 13/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0022 - mae: 0.0263 - val_loss: 0.0038 - val_mae: 0.0506
Epoch 14/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0020 - mae: 0.0262 - val_loss: 0.0032 - val_mae: 0.0459
Epoch 15/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0019 - mae: 0.0260 - val_loss: 0.0028 - val_mae: 0.0435
Epoch 16/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0018 - mae: 0.0259 - val_loss: 0.0022 - val_mae: 0.0361
Epoch 17/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0017 - mae: 0.0253 - val_loss: 0.0023 - val_mae: 0.0346
Epoch 18/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0016 - mae: 0.0256 - val_loss: 0.0015 - val_mae: 0.0258
Epoch 19/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0016 - mae: 0.0253 - val_loss: 0.0017 - val_mae: 0.0325
Epoch 20/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 121ms/step - loss: 0.0015 - mae: 0.0252 - val_loss: 0.0012 - val_mae: 0.0228
Epoch 21/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0015 - mae: 0.0246 - val_loss: 0.0013 - val_mae: 0.0269
Epoch 22/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 118ms/step - loss: 0.0014 - mae: 0.0246 - val_loss: 0.0011 - val_mae: 0.0215
Epoch 23/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0014 - mae: 0.0252 - val_loss: 0.0016 - val_mae: 0.0272
Epoch 24/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 118ms/step - loss: 0.0014 - mae: 0.0247 - val_loss: 0.0010 - val_mae: 0.0181
Epoch 25/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0013 - mae: 0.0244 - val_loss: 0.0011 - val_mae: 0.0214
Epoch 26/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 118ms/step - loss: 0.0013 - mae: 0.0244 - val_loss: 0.0010 - val_mae: 0.0201
Epoch 27/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0013 - mae: 0.0239 - val_loss: 9.7362e-04 - val_mae: 0.0191
Epoch 28/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0014 - mae: 0.0249 - val_loss: 0.0011 - val_mae: 0.0211
Epoch 29/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 118ms/step - loss: 0.0013 - mae: 0.0242 - val_loss: 0.0012 - val_mae: 0.0238
Epoch 30/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 118ms/step - loss: 0.0014 - mae: 0.0250 - val_loss: 0.0010 - val_mae: 0.0203
Epoch 31/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0013 - mae: 0.0244 - val_loss: 0.0010 - val_mae: 0.0213
Epoch 32/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 117ms/step - loss: 0.0012 - mae: 0.0237 - val_loss: 0.0010 - val_mae: 0.0191
------Training completed for: CYC_Grove Road Totem

----- Evaluating model for: CYC_Grove Road Totem (4/19)
251/251 ━━━━━━━━━━━━━━━━━━━━ 7s 25ms/step
Evaluation Metrics:
 -RMSE : 41.39
 -MAE  : 22.43
 -MAPE : 47.37%
 -R²   : 0.8801

--- Processing target 4 out of 19: CYC_North Strand Rd N B

Training model for: CYC_North Strand Rd N B ===
Epoch 1/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 14s 146ms/step - loss: 0.0283 - mae: 0.0545 - val_loss: 0.0176 - val_mae: 0.0031
Epoch 2/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0183 - mae: 0.0413 - val_loss: 0.0122 - val_mae: 0.0422
Epoch 3/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0120 - mae: 0.0347 - val_loss: 0.0082 - val_mae: 0.0412
Epoch 4/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0082 - mae: 0.0305 - val_loss: 0.0057 - val_mae: 0.0389
Epoch 5/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 121ms/step - loss: 0.0058 - mae: 0.0280 - val_loss: 0.0044 - val_mae: 0.0427
Epoch 6/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0044 - mae: 0.0259 - val_loss: 0.0033 - val_mae: 0.0393
Epoch 7/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 118ms/step - loss: 0.0033 - mae: 0.0240 - val_loss: 0.0024 - val_mae: 0.0323
Epoch 8/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 121ms/step - loss: 0.0027 - mae: 0.0232 - val_loss: 0.0018 - val_mae: 0.0256
Epoch 9/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 118ms/step - loss: 0.0023 - mae: 0.0223 - val_loss: 0.0015 - val_mae: 0.0243
Epoch 10/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0020 - mae: 0.0219 - val_loss: 0.0011 - val_mae: 0.0121
Epoch 11/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0017 - mae: 0.0212 - val_loss: 0.0010 - val_mae: 0.0142
Epoch 12/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0016 - mae: 0.0215 - val_loss: 7.5765e-04 - val_mae: 0.0081
Epoch 13/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0014 - mae: 0.0208 - val_loss: 5.9893e-04 - val_mae: 0.0040
Epoch 14/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0013 - mae: 0.0207 - val_loss: 5.5562e-04 - val_mae: 0.0044
Epoch 15/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 121ms/step - loss: 0.0012 - mae: 0.0203 - val_loss: 5.0584e-04 - val_mae: 0.0041
Epoch 16/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0012 - mae: 0.0205 - val_loss: 4.9333e-04 - val_mae: 0.0042
Epoch 17/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0012 - mae: 0.0208 - val_loss: 4.2939e-04 - val_mae: 0.0019
Epoch 18/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0011 - mae: 0.0205 - val_loss: 4.1388e-04 - val_mae: 0.0020
Epoch 19/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0011 - mae: 0.0204 - val_loss: 4.7707e-04 - val_mae: 0.0034
Epoch 20/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0011 - mae: 0.0201 - val_loss: 3.5481e-04 - val_mae: 0.0012
Epoch 21/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 5s 122ms/step - loss: 0.0011 - mae: 0.0203 - val_loss: 3.8146e-04 - val_mae: 0.0017
Epoch 22/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0010 - mae: 0.0203 - val_loss: 3.1787e-04 - val_mae: 1.7090e-04
Epoch 23/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0010 - mae: 0.0200 - val_loss: 3.0909e-04 - val_mae: 2.7921e-04
Epoch 24/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 118ms/step - loss: 0.0010 - mae: 0.0198 - val_loss: 2.9503e-04 - val_mae: 0.0000e+00
Epoch 25/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 118ms/step - loss: 0.0010 - mae: 0.0201 - val_loss: 4.5549e-04 - val_mae: 0.0026
Epoch 26/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0011 - mae: 0.0212 - val_loss: 5.6623e-04 - val_mae: 0.0032
Epoch 27/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 118ms/step - loss: 9.8219e-04 - mae: 0.0195 - val_loss: 3.2799e-04 - val_mae: 0.0014
Epoch 28/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0010 - mae: 0.0199 - val_loss: 5.4125e-04 - val_mae: 0.0047
Epoch 29/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0010 - mae: 0.0200 - val_loss: 2.9419e-04 - val_mae: 2.9145e-04
Epoch 30/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 9.3728e-04 - mae: 0.0194 - val_loss: 0.0025 - val_mae: 0.0225
Epoch 31/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0013 - mae: 0.0245 - val_loss: 0.0010 - val_mae: 0.0081
Epoch 32/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 118ms/step - loss: 0.0011 - mae: 0.0210 - val_loss: 2.8783e-04 - val_mae: 2.1445e-04
Epoch 33/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0011 - mae: 0.0203 - val_loss: 2.7591e-04 - val_mae: 7.0600e-05
Epoch 34/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 9.7059e-04 - mae: 0.0197 - val_loss: 3.2400e-04 - val_mae: 0.0020
Epoch 35/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 117ms/step - loss: 9.5073e-04 - mae: 0.0194 - val_loss: 2.7699e-04 - val_mae: 6.9789e-04
Epoch 36/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 121ms/step - loss: 9.6579e-04 - mae: 0.0199 - val_loss: 3.3627e-04 - val_mae: 0.0025
Epoch 37/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 9.2661e-04 - mae: 0.0194 - val_loss: 2.5569e-04 - val_mae: 2.6661e-04
Epoch 38/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 118ms/step - loss: 0.0010 - mae: 0.0200 - val_loss: 2.6308e-04 - val_mae: 5.5654e-04
Epoch 39/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 9.3213e-04 - mae: 0.0197 - val_loss: 2.9279e-04 - val_mae: 0.0012
Epoch 40/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 118ms/step - loss: 9.3301e-04 - mae: 0.0193 - val_loss: 2.9967e-04 - val_mae: 0.0015
Epoch 41/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 9.5134e-04 - mae: 0.0196 - val_loss: 2.4220e-04 - val_mae: 6.3211e-05
Epoch 42/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 9.2071e-04 - mae: 0.0191 - val_loss: 2.3774e-04 - val_mae: 0.0000e+00
Epoch 43/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 9.1398e-04 - mae: 0.0195 - val_loss: 2.4424e-04 - val_mae: 1.5270e-04
Epoch 44/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 9.4963e-04 - mae: 0.0196 - val_loss: 2.8198e-04 - val_mae: 0.0016
Epoch 45/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 118ms/step - loss: 9.3513e-04 - mae: 0.0200 - val_loss: 2.3963e-04 - val_mae: 6.9790e-05
Epoch 46/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 118ms/step - loss: 9.2925e-04 - mae: 0.0194 - val_loss: 2.4004e-04 - val_mae: 1.0396e-04
Epoch 47/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 9.4520e-04 - mae: 0.0197 - val_loss: 2.8584e-04 - val_mae: 0.0024
------Training completed for: CYC_North Strand Rd N B

----- Evaluating model for: CYC_North Strand Rd N B (5/19)
251/251 ━━━━━━━━━━━━━━━━━━━━ 7s 24ms/step
Evaluation Metrics:
 -RMSE : 0.00
 -MAE  : 0.00
 -MAPE : nan%
 -R²   : 1.0000

--- Processing target 5 out of 19: CYC_Richmond Street Cyclists 1 Merged

Training model for: CYC_Richmond Street Cyclists 1 Merged ===
Epoch 1/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 14s 149ms/step - loss: 0.0340 - mae: 0.0791 - val_loss: 0.0290 - val_mae: 0.0865
Epoch 2/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 118ms/step - loss: 0.0223 - mae: 0.0462 - val_loss: 0.0230 - val_mae: 0.0854
Epoch 3/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0161 - mae: 0.0349 - val_loss: 0.0186 - val_mae: 0.0775
Epoch 4/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0120 - mae: 0.0304 - val_loss: 0.0163 - val_mae: 0.0787
Epoch 5/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 118ms/step - loss: 0.0093 - mae: 0.0287 - val_loss: 0.0137 - val_mae: 0.0763
Epoch 6/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 120ms/step - loss: 0.0074 - mae: 0.0274 - val_loss: 0.0122 - val_mae: 0.0752
Epoch 7/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0059 - mae: 0.0264 - val_loss: 0.0112 - val_mae: 0.0740
Epoch 8/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 118ms/step - loss: 0.0049 - mae: 0.0258 - val_loss: 0.0098 - val_mae: 0.0684
Epoch 9/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 119ms/step - loss: 0.0041 - mae: 0.0253 - val_loss: 0.0090 - val_mae: 0.0692
Epoch 10/100

## **3.6 RESULTS**

In [ ]:
results = pd.DataFrame.from_dict(results, orient="index")
results.index.name = "Target"
results = results.reset_index()
print("\nSummary of results CNN-LSTM without coordinates:")
results

Summary of results CNN-LSTM without coordinates:

,Target,RMSE,MAE,MAPE,R2
0,CYC_Clontarf James Larkin Rd,18.883928,11.722347,62.211089,0.758905
1,CYC_Clontarf Pebble Beach Carpark,27.761920,17.818102,88.261566,0.743523
2,CYC_Grove Road Totem,41.386365,22.434457,47.366530,0.880121
3,CYC_North Strand Rd N B,0.000000,0.000000,NaN,1.000000
4,CYC_Richmond Street Cyclists 1 Merged,39.551493,24.278152,137.393276,0.265976
5,CYC_Richmond Street Cyclists 2 Merged,25.229261,14.982272,54.676945,0.648328
6,FTF_Aston Quay Merged,1694.930461,1517.101124,172.005987,-0.857670
7,FTF_Capel St Mary St Merged,1057.876128,916.473658,418.042156,-2.162089
8,FTF_College St Dame St Merged,278.115970,181.217228,61.174618,0.566426
9,FTF_Dame St Merged,457.553778,349.499001,390.951687,-1.051619
10,FTF_Dolier St Burgh Quay Merged,1164.021850,1114.013483,1005.723538,-14.820458
11,FTF_Grafton St Monsoon Merged,1238.590537,1084.665793,754.174622,-0.269759
12,FTF_Grafton St Nassau St Suffolk St,126.507465,83.795131,126.742626,0.692837
13,FTF_Henry St Merged,6140.000184,4484.051685,2594.943027,-13.643491
14,FTF_Mary St Merged,227.876959,147.590137,71.262975,0.770701
15,FTF_Oconnell St Princes St North Merged,963.645609,830.131461,145.951899,-1.861287
16,FTF_Talbot St Guineys Merged,1514.519406,1481.784395,4382.467417,-23.581309
17,FTF_Westmoreland St East Fleet St Merged,1404.430021,1352.572160,NaN,0.000000
18,FTF_Westmoreland St West Merged,422.149267,334.627216,184.974060,0.453011

### **3.7 PREDICTIONS**

In [ ]:
# Dictionary with DataFrames for all targets
predictions = {}

for target_name in targets:
    print(f"\nPredicting values for: {target_name}")
    X_test, y_test = test_sets[target_name]
    target_scaler = target_scaler_dict[target_name]

    # Scale and descale predictions
    y_pred_scaled = trained_models[target_name].predict(X_test)
    y_pred = target_scaler.inverse_transform(y_pred_scaled)
    y_true = target_scaler.inverse_transform(y_test.reshape(-1, 1))

    # Predicted values flatten to 1D arrays
    y_pred = y_pred.reshape(-1)
    y_true = y_true.reshape(-1)

    # Index of start with date and time
    # Sequence length in LSTM sequences
    seq_len = sequence_length
    n_total = len(y_cnn_lstm_dict[target_name])
    n_train = int(n_total * 0.7)
    n_val = int(n_total * 0.15)
    start_test_idx = seq_len + n_train + n_val

    datest = data["date and time"].iloc[start_test_idx:].reset_index(drop=True)

    # DataFrame with only whole numbers and avoiding negative values
    predsDataFrame = pd.DataFrame({
        "date and time": datest,
        "Real": np.maximum(np.round(y_true).astype(int), 0),
        "CNNLSTM_nocoords": np.maximum(np.round(y_pred).astype(int), 0)
    })
    predictions[target_name] = predsDataFrame
    print(predsDataFrame.head())

# Merge all targets in a single DataFrame
allpreds = pd.concat(
    [dataframe.assign(Target=target) for target, dataframe in predictions.items()],
    ignore_index=True
)

Predicting values for: CYC_Clontarf James Larkin Rd
251/251 ━━━━━━━━━━━━━━━━━━━━ 5s 22ms/step
         date and time  Real  CNNLSTM_nocoords
0  2024-03-07 06:00:00    20                23
1  2024-03-07 07:00:00    49                50
2  2024-03-07 08:00:00    70                67
3  2024-03-07 09:00:00    51                45
4  2024-03-07 10:00:00    31                41

Predicting values for: CYC_Clontarf Pebble Beach Carpark
251/251 ━━━━━━━━━━━━━━━━━━━━ 5s 22ms/step
         date and time  Real  CNNLSTM_nocoords
0  2024-03-07 06:00:00    26                37
1  2024-03-07 07:00:00    75                67
2  2024-03-07 08:00:00   105                91
3  2024-03-07 09:00:00    75                71
4  2024-03-07 10:00:00    33                69

Predicting values for: CYC_Grove Road Totem
251/251 ━━━━━━━━━━━━━━━━━━━━ 5s 22ms/step
         date and time  Real  CNNLSTM_nocoords
0  2024-03-07 06:00:00   125                77
1  2024-03-07 07:00:00   309               215
2  2024-03-07 08:00:00   607               477
3  2024-03-07 09:00:00   247               254
4  2024-03-07 10:00:00    94               102

Predicting values for: CYC_North Strand Rd N B
251/251 ━━━━━━━━━━━━━━━━━━━━ 6s 22ms/step
         date and time  Real  CNNLSTM_nocoords
0  2024-03-07 06:00:00     0                 0
1  2024-03-07 07:00:00     0                 0
2  2024-03-07 08:00:00     0                 0
3  2024-03-07 09:00:00     0                 0
4  2024-03-07 10:00:00     0                 0

Predicting values for: CYC_Richmond Street Cyclists 1 Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 5s 22ms/step
         date and time  Real  CNNLSTM_nocoords
0  2024-03-07 06:00:00    21               129
1  2024-03-07 07:00:00    88               166
2  2024-03-07 08:00:00   244               199
3  2024-03-07 09:00:00   135               187
4  2024-03-07 10:00:00    75               110

Predicting values for: CYC_Richmond Street Cyclists 2 Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 6s 22ms/step
         date and time  Real  CNNLSTM_nocoords
0  2024-03-07 06:00:00    12                 3
1  2024-03-07 07:00:00    38                10
2  2024-03-07 08:00:00    53                16
3  2024-03-07 09:00:00    37                19
4  2024-03-07 10:00:00    19                18

Predicting values for: FTF_Aston Quay Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 5s 22ms/step
         date and time  Real  CNNLSTM_nocoords
0  2024-03-07 06:00:00  1524              3338
1  2024-03-07 07:00:00  2191              4124
2  2024-03-07 08:00:00  4623              4504
3  2024-03-07 09:00:00  3941              4668
4  2024-03-07 10:00:00  2430              4664

Predicting values for: FTF_Capel St Mary St Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 5s 22ms/step
         date and time  Real  CNNLSTM_nocoords
0  2024-03-07 06:00:00   348               767
1  2024-03-07 07:00:00   305               878
2  2024-03-07 08:00:00  1026              1101
3  2024-03-07 09:00:00  1098              1393
4  2024-03-07 10:00:00  1721              1716

Predicting values for: FTF_College St Dame St Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 5s 21ms/step
         date and time  Real  CNNLSTM_nocoords
0  2024-03-07 06:00:00   250               100
1  2024-03-07 07:00:00   533               330
2  2024-03-07 08:00:00  1243              1170
3  2024-03-07 09:00:00   966              1031
4  2024-03-07 10:00:00   809               921

Predicting values for: FTF_Dame St Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 5s 22ms/step
         date and time  Real  CNNLSTM_nocoords
0  2024-03-07 06:00:00   293               415
1  2024-03-07 07:00:00   480               550
2  2024-03-07 08:00:00   663               643
3  2024-03-07 09:00:00   702               672
4  2024-03-07 10:00:00   596               690

Predicting values for: FTF_Dolier St Burgh Quay Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 5s 22ms/step
         date and time  Real  CNNLSTM_nocoords
0  2024-03-07 06:00:00   291              1165
1  2024-03-07 07:00:00   494              1380
2  2024-03-07 08:00:00   823              1502
3  2024-03-07 09:00:00   752              1537
4  2024-03-07 10:00:00   535              1547

Predicting values for: FTF_Grafton St Monsoon Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 5s 22ms/step
         date and time  Real  CNNLSTM_nocoords
0  2024-03-07 06:00:00  1867              2378
1  2024-03-07 07:00:00  1909              2764
2  2024-03-07 08:00:00  1718              3088
3  2024-03-07 09:00:00  2174              3342
4  2024-03-07 10:00:00  2111              3552

Predicting values for: FTF_Grafton St Nassau St Suffolk St
251/251 ━━━━━━━━━━━━━━━━━━━━ 5s 21ms/step
         date and time  Real  CNNLSTM_nocoords
0  2024-03-07 06:00:00    76               136
1  2024-03-07 07:00:00   162               229
2  2024-03-07 08:00:00   469               424
3  2024-03-07 09:00:00   330               385
4  2024-03-07 10:00:00   273               370

Predicting values for: FTF_Henry St Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 5s 22ms/step
         date and time  Real  CNNLSTM_nocoords
0  2024-03-07 06:00:00   458              1065
1  2024-03-07 07:00:00   925              1915
2  2024-03-07 08:00:00  2353              3164
3  2024-03-07 09:00:00  3062              4296
4  2024-03-07 10:00:00  4369              5616

Predicting values for: FTF_Mary St Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 5s 22ms/step
         date and time  Real  CNNLSTM_nocoords
0  2024-03-07 06:00:00    59               126
1  2024-03-07 07:00:00    87               201
2  2024-03-07 08:00:00   286               294
3  2024-03-07 09:00:00   334               398
4  2024-03-07 10:00:00   918               554

Predicting values for: FTF_Oconnell St Princes St North Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 5s 22ms/step
         date and time  Real  CNNLSTM_nocoords
0  2024-03-07 06:00:00   366               574
1  2024-03-07 07:00:00   598               787
2  2024-03-07 08:00:00  1050              1039
3  2024-03-07 09:00:00   760              1056
4  2024-03-07 10:00:00   720              1149

Predicting values for: FTF_Talbot St Guineys Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 5s 22ms/step
         date and time  Real  CNNLSTM_nocoords
0  2024-03-07 06:00:00     0              1378
1  2024-03-07 07:00:00     0              1409
2  2024-03-07 08:00:00     0              1480
3  2024-03-07 09:00:00     0              1545
4  2024-03-07 10:00:00     0              1611

Predicting values for: FTF_Westmoreland St East Fleet St Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 5s 22ms/step
         date and time  Real  CNNLSTM_nocoords
0  2024-03-07 06:00:00     0              1632
1  2024-03-07 07:00:00     0              1700
2  2024-03-07 08:00:00     0              1718
3  2024-03-07 09:00:00     0              1634
4  2024-03-07 10:00:00     0              1540

Predicting values for: FTF_Westmoreland St West Merged
251/251 ━━━━━━━━━━━━━━━━━━━━ 5s 22ms/step
         date and time  Real  CNNLSTM_nocoords
0  2024-03-07 06:00:00   325               457
1  2024-03-07 07:00:00   594               534
2  2024-03-07 08:00:00   934               619
3  2024-03-07 09:00:00   833               657
4  2024-03-07 10:00:00   930               707

In [ ]:
allpreds.head(20)

          date and time  Real  CNNLSTM_nocoords                        Target
0   2024-03-07 06:00:00    20                23  CYC_Clontarf James Larkin Rd
1   2024-03-07 07:00:00    49                50  CYC_Clontarf James Larkin Rd
2   2024-03-07 08:00:00    70                67  CYC_Clontarf James Larkin Rd
3   2024-03-07 09:00:00    51                45  CYC_Clontarf James Larkin Rd
4   2024-03-07 10:00:00    31                41  CYC_Clontarf James Larkin Rd
5   2024-03-07 11:00:00    32                41  CYC_Clontarf James Larkin Rd
6   2024-03-07 12:00:00    36                44  CYC_Clontarf James Larkin Rd
7   2024-03-07 13:00:00    33                42  CYC_Clontarf James Larkin Rd
8   2024-03-07 14:00:00    23                43  CYC_Clontarf James Larkin Rd
9   2024-03-07 15:00:00    25                50  CYC_Clontarf James Larkin Rd
10  2024-03-07 16:00:00    39                60  CYC_Clontarf James Larkin Rd
11  2024-03-07 17:00:00    68                69  CYC_Clontarf James Larkin Rd
12  2024-03-07 18:00:00    62                71  CYC_Clontarf James Larkin Rd
13  2024-03-07 19:00:00    33                47  CYC_Clontarf James Larkin Rd
14  2024-03-07 20:00:00     8                24  CYC_Clontarf James Larkin Rd
15  2024-03-07 21:00:00     7                10  CYC_Clontarf James Larkin Rd
16  2024-03-07 22:00:00     6                 4  CYC_Clontarf James Larkin Rd
17  2024-03-07 23:00:00     1                 0  CYC_Clontarf James Larkin Rd
18  2024-03-08 00:00:00     4                 0  CYC_Clontarf James Larkin Rd
19  2024-03-08 01:00:00     2                 0  CYC_Clontarf James Larkin Rd

## **4. RESULTS TO AZURE BLOB STORAGE**

In [ ]:
def save_blob(data, filename):
    try:
        blob_name = f"{CONTAINER_NAME}/{filename}"
        csv_data = data.to_csv(index=False)
        with fs.open(blob_name, "w") as f:
            f.write(csv_data)
        print(f"Saved to {blob_name}")
    except Exception as e:
        print(f"Error saving data to blob storage: {str(e)}")
        return False

In [ ]:
CONTAINER_NAME = "results"

save_blob(results, "rcnnlstm_nocoords.csv")

Saved to results/rcnnlstm_nocoords.csv

In [ ]:
CONTAINER_NAME = "predictions"

save_blob(allpreds, "pred_cnnlstm_nocoords.csv")

Saved to predictions/pred_cnnlstm_nocoords.csv